using System.Collections.Generic;
using Newtonsoft.Json;

namespace AirSoftAutomationFramework.Objects.DTOs
{
    public class TradingLanguage
    {
        public string _id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string platform { get; set; }

        [JsonProperty("translations")]
        public TradingTranslation tradingTranslations { get; set; }
        public bool active { get; set; }
        public bool @default { get; set; }

        [JsonProperty("data")]
        public List<LanguageData> languageData { get; set; }
    }

    public class TradingTranslation
    {
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string EQUITY { get; set; }
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string M_MARGIN { get; set; }
        public string BALANCE { get; set; }
        public string AVAILABLE { get; set; }
        public string CLOSED_PROFIT_LOSS { get; set; }
        public string PROFIT_LOSS { get; set; }
        public string PROFILE { get; set; }
        public string LOGOUT { get; set; }
        public string CHAT { get; set; }
        public string CHAT_CONNECTION_UNAVAILABLE { get; set; }
        public string DEPOSIT { get; set; }
        public string WITHDRAWAL { get; set; }
        public string READ_ALL { get; set; }
        public string PERSONAL_INFORMATIONS { get; set; }
        public string PERSONAL_INFO { get; set; }
        public string ID { get; set; }
        public string ID_CAPITALIZED { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string COUNTRY { get; set; }
        public string COUNTRY_CAPITALIZED { get; set; }
        public string STATE { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string ACCOUNT_TYPE_CAPITALIZED { get; set; }
        public string BASE_CURRENCY { get; set; }
        public string BASE_CURRENCY_CAPITALIZED { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string CLIENT_ACTIVE_STATUS { get; set; }
        public string CLIENT_PENDING_STATUS { get; set; }
        public string CLIENT_CAN_DEPOSIT_STATUS { get; set; }
        public string CHANGE_PASSWORD { get; set; }
        public string PASSWORD_CAPITALIZED { get; set; }
        public string ANTI_PHISHING_CAPITALIZED { get; set; }
        public string PROOF_OF_IDENTITY { get; set; }
        public string PROOF_OF_IDENTITY_EXPLANATION { get; set; }
        public string PROOF_OF_IDENTITY_MODAL_EXPLANATION { get; set; }
        public string PROOF_OF_IDENTITY_MODAL_DOCUMENTATION { get; set; }
        public string THIS_COULD_BE { get; set; }
        public string THIS_COULD_BE_IDENTITY_EXPLANATION { get; set; }
        public string THE_DOCUMENT_MUST_BE { get; set; }
        public string THE_DOCUMENT_MUST_BE_IDENTITY_EXPLANATION { get; set; }
        public string PROOF_OF_RESIDENCY { get; set; }
        public string PROOF_OF_RESIDENCY_EXPLANATION { get; set; }
        public string PROOF_OF_RESIDENCY_MODAL_EXPLANATION { get; set; }
        public string THIS_COULD_BE_RESIDENCY_EXPLANATION { get; set; }
        public string THE_DOCUMENT_MUST_BE_RESIDENCY_EXPLANATION { get; set; }
        public string CREDIT_DEBIT_CARD_DOCUMENTATION { get; set; }
        public string CREDIT_DEBIT_CARD_DOCUMENTATION_SHORT { get; set; }
        public string FRONT { get; set; }
        public string BACK { get; set; }
        public string UPLOAD_FRONT { get; set; }
        public string UPLOAD_BACK { get; set; }
        public string KYC_STATUS { get; set; }
        public string GENERAL_KYC { get; set; }
        public string CREDIT_DEBIT_FRONT { get; set; }
        public string CREDIT_DEBIT_BACK { get; set; }
        public string CC_FRONT { get; set; }
        public string CC_BACK { get; set; }
        public string CREDIT_DEBIT_CARD_DOCUMENTATION_EXPLANATION { get; set; }
        public string CREDIT_DEBIT_CARD_DOCUMENTATION_MODAL_EXPLANATION { get; set; }
        public string DECLARATION_OF_DEPOSIT { get; set; }
        public string DECLARATION_OF_DEPOSIT_EXPLANATION { get; set; }
        public string DECLARATION_OF_DEPOSIT_STEPS1 { get; set; }
        public string DECLARATION_OF_DEPOSIT_STEPS2 { get; set; }
        public string DECLARATION_OF_DEPOSIT_STEPS3 { get; set; }
        public string DECLARATION_OF_DEPOSIT_DOCUMENT_MUST_BE_EXPLANATION { get; set; }
        public string SEE_EXAMPLE { get; set; }
        public string DOWNLOAD { get; set; }
        public string UPLOAD { get; set; }
        public string STATUS { get; set; }
        public string WAITING { get; set; }
        public string NAME { get; set; }
        public string ADDRESS { get; set; }
        public string PHOTO { get; set; }
        public string UNIQE_PERSONAL_NUMBER { get; set; }
        public string UNIQE_PERSONAL_NUMBER_EXPLANATION { get; set; }
        public string EXPIRATION_DATE { get; set; }
        public string IF_REQUIRED { get; set; }
        public string EXAMPLES_OF_DOCUMENTS { get; set; }
        public string SIGNITURE { get; set; }
        public string SIGNITURE_EXPLANATION { get; set; }
        public string ACCOUNT_INFO { get; set; }
        public string CONTACT_US { get; set; }
        public string REAL { get; set; }
        public string AUTO_LOGIN { get; set; }
        public string CAN_DEPOSIT { get; set; }
        public string TRADE { get; set; }
        public string ASSET_OPEN { get; set; }
        public string OPEN_TRADES { get; set; }
        public string CLOSED_TRADES { get; set; }
        public string PENDING_ORDERS { get; set; }
        public string MY_PROFILE { get; set; }
        public string ACTIVATED_ON_SOCIAL_TRADE { get; set; }
        public string LIVE_TV { get; set; }
        public string NEWS { get; set; }
        public string GAINERS_LOSERS { get; set; }
        public string FAVORITES { get; set; }
        public string ALERTS { get; set; }
        public string ACTIVITIES { get; set; }
        public string PORTFOLIO { get; set; }
        public string WATCHLIST { get; set; }
        public string OPEN_TIME { get; set; }
        public string TRADE_CLOSED_VOLUME { get; set; }
        public string INSTRUMENT { get; set; }
        public string TYPE { get; set; }
        public string AMOUNT { get; set; }
        public string OPEN_PRICE { get; set; }
        public string CLOSE_PRICE { get; set; }
        public string CLOSE_TIME { get; set; }
        public string CURRENT_PRICE { get; set; }
        public string CLOSE_AT_PROFIT { get; set; }
        public string CLOSE_AT_LOSS { get; set; }
        public string SWAP { get; set; }
        public string PROFIT { get; set; }
        public string ACTION { get; set; }
        public string SHORT { get; set; }
        public string LONG { get; set; }
        public string CHANGE { get; set; }
        public string LOW_HIGH { get; set; }
        public string MIN_MARGIN { get; set; }
        public string MIN_USAGE { get; set; }
        public string CURRENT_RATE { get; set; }
        public string OPEN_RATE { get; set; }
        public string TICKET { get; set; }
        public string VALUE { get; set; }
        public string EXPIRED { get; set; }
        public string REQUIRED_MARGIN { get; set; }
        public string MAINTENANCE_MARGIN { get; set; }
        public string COMMISSION { get; set; }
        public string ADVANCED_ORDER { get; set; }
        public string CLOSE_AT_PROFIT_WHEN_RATE_IS { get; set; }
        public string CLOSE_AT_LOSS_WHEN_RATE_IS { get; set; }
        public string ONLY { get; set; }
        public string WHEN_RATE_IS { get; set; }
        public string DETAILS { get; set; }
        public string ORDER { get; set; }
        public string STOP_LOSS { get; set; }
        public string TAKE_PROFIT { get; set; }
        public string CLOSE { get; set; }
        public string CANCEL { get; set; }
        public string SUBMIT { get; set; }
        public string FILE_TYPE_ERROR { get; set; }
        public string FILE_SIZE_ERROR { get; set; }
        public string TICK { get; set; }

        [JsonProperty("1_MINUTE")]
        public string OneMinutes { get; set; }

        [JsonProperty("5_MINUTES")]
        public string FiveMinutes { get; set; }

        [JsonProperty("15_MINUTES")]
        public string FifteenMinutes { get; set; }

        [JsonProperty("30_MINUTES")]
        public string thirtyMinutes { get; set; }

        [JsonProperty("1_HOUR")]
        public string OneHour { get; set; }

        [JsonProperty("1_DAY")]
        public string OneDay { get; set; }

        [JsonProperty("1_WEEK")]
        public string OneWeek { get; set; }

        [JsonProperty("1_MONTH")]
        public string OneMonth { get; set; }
        public string BID { get; set; }
        public string ASK { get; set; }
        public string CLOSED { get; set; }
        public string FROM { get; set; }
        public string TO { get; set; }
        public string OPEN_HOURS { get; set; }
        public string TRADING_IS_CLOSED { get; set; }
        public string FIRST_NAME_IS_REQUIRED { get; set; }
        public string LAST_NAME_IS_REQUIRED { get; set; }
        public string BIRTHDAY_IS_REQUIRED { get; set; }
        public string ADDRESS_IS_REQUIRED { get; set; }
        public string CITY_IS_REQUIRED { get; set; }
        public string COUNTRY_IS_REQUIRED { get; set; }
        public string STATE_IS_REQUIRED { get; set; }
        public string POSTAL_CODE_IS_REQUIRED { get; set; }
        public string PHONE_NUMBER_IS_REQUIRED { get; set; }
        public string EMAIL_IS_REQUIRED { get; set; }
        public string EMAIL_IS_INVALID { get; set; }
        public string AMOUNT_IS_REQUIRED { get; set; }
        public string PLEASE_CHOOSE_PAYMENT_PROVIDER { get; set; }
        public string CHOOSE_METHOD_FOR_DEPOSIT_FUNDS { get; set; }
        public string CONVERTER { get; set; }
        public string CLOSE_PAYMENT_WINDOW { get; set; }
        public string PAYMENT_DETAILS { get; set; }
        public string AMOUNT_TO_DEPOSIT { get; set; }
        public string BIRTHDAY { get; set; }
        public string CITY { get; set; }
        public string POSTAL_CODE { get; set; }
        public string EMAIL { get; set; }
        public string UPDATE_PROFILE_DETAILS { get; set; }
        public string DREAMSPAY { get; set; }
        public string ADD_GRAPH { get; set; }
        public string CHANGE_GRAPH { get; set; }
        public string SELECT_ASSET { get; set; }
        public string SELECT_STATE { get; set; }
        public string LAST_DEPOSITS { get; set; }
        public string FORGOT_PASSWORD { get; set; }
        public string USERNAME_REQUIRED { get; set; }
        public string INVALID_EMAIL { get; set; }
        public string MINIMUM_AMOUNT { get; set; }
        public string LEVERAGE { get; set; }
        public string SWAP_TIME { get; set; }
        public string TRADING_HOURS { get; set; }
        public string TRADING_HOURS_GMT { get; set; }
        public string EMAIL_REQUIRED { get; set; }
        public string SELL { get; set; }
        public string BUY { get; set; }
        public string RATE { get; set; }
        public string ALERT_WHEN_RATE_IS { get; set; }
        public string AMOUNT_WHEN_ASSET_OPEN { get; set; }
        public string MENU { get; set; }
        public string SETTINGS { get; set; }
        public string HISTORY { get; set; }
        public string DATE { get; set; }
        public string EDIT { get; set; }
        public string DELETE { get; set; }
        public string AMOUNT_TO_WITHDRAWAL { get; set; }
        public string AVAILABLE_TO_WITHDRAWAL { get; set; }
        public string CREDIT_CARD { get; set; }
        public string CREDIT_CARD_FRONT { get; set; }
        public string CREDIT_CARD_BACK { get; set; }
        public string BANK { get; set; }
        public string BTC_WALLET { get; set; }
        public string FULL_BTC_WALLET_ADDRESS { get; set; }
        public string BANK_NAME { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
        public string BANK_ADDRESS { get; set; }
        public string BANK_BRANCH { get; set; }
        public string SEND_REQUEST { get; set; }
        public string BY_CLIKING_ON_THE_BUTTON_BELOW_YOU_AGREE_TO_THE_TERMS_AND_CONDITIONS { get; set; }
        public string CARD_OWNER_NAME { get; set; }
        public string CARD_LAST_DIGITS { get; set; }
        public string BTC_ADDRESS_CONFIRMATION { get; set; }
        public string INVALID_WALLET_ADDRESS { get; set; }
        public string INVALID_CHARACTERS_ADDRESS { get; set; }
        public string INVALID_CHARACTERS_VALIDATION { get; set; }
        public string FIRST_FOUR_DIGITS { get; set; }
        public string LAST_FOUR_DIGITS { get; set; }
        public string VALID { get; set; }
        public string INVALID { get; set; }
        public string VERIFIED { get; set; }
        public string FAILED { get; set; }
        public string PARTIALLY_VERIFIED { get; set; }
        public string FULLY_VERIFIED { get; set; }
        public string NOT_VERIFIED { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string ROLL_OVER_DESCRIPTION { get; set; }
        public string EXPIRY_DESCRIPTION { get; set; }
        public string LAST_DIGITS_CAN_NOT_EXCEED_4_NUMBERS { get; set; }
        public string LAST_DIGITS_MUST_BE_NUMERIC { get; set; }
        public string WALLET_VERIFICATION_FAILED { get; set; }
        public string AMOUNT_CAN_NOT_EXCEED_AVAILABLE_WITHDRAWAL { get; set; }
        public string BANK_NAME_IS_REQUIRED { get; set; }
        public string ACCOUNT_NAME_IS_REQUIRED { get; set; }
        public string SWIFT_IS_REQUIRED { get; set; }
        public string IBAN_IS_REQUIRED { get; set; }
        public string BANK_ADDRESS_IS_REQUIRED { get; set; }
        public string BANK_BRAHCN_IS_REQUIRED { get; set; }
        public string CARD_OWNER_NAME_IS_REQUIRED { get; set; }
        public string EXPIRE_DATE_IS_REQUIRED { get; set; }
        public string CVV_IS_REQUIRED { get; set; }
        public string CVV_CAN_NOT_EXCEED_3_NUMBERS { get; set; }
        public string CHOOSE_WITHDRAWAL_PAYMENT_METHOD { get; set; }
        public string INDICATORS { get; set; }
        public string INDICATORS_OPTIONS { get; set; }
        public string AD_ACCUMULATION_DISTRIBUTION { get; set; }
        public string ATR_AVERAGE_TRUE_RANGE { get; set; }
        public string BOLLINGER_BANDS { get; set; }
        public string CCI_COMMODITY_CHANNEL_INDEX { get; set; }
        public string CMF_CHAIKIN_MONEY_FLOW { get; set; }
        public string EMA_EXPONENTIAL_MOVING_AVERAGE { get; set; }
        public string ICHIMOKU_KINKO_HYO { get; set; }
        public string MACD_MOVING_AVERAGE_CONVERGENCE_DIVERGENCE { get; set; }
        public string MFI_MONEY_FLOW_INDEX { get; set; }
        public string MOMENTUM { get; set; }
        public string PIVOT_POINTS { get; set; }
        public string PRICE_ENVELOPES { get; set; }
        public string PSAR_PARABOLIC_SAR { get; set; }
        public string ROC_RATE_OF_CHANGE { get; set; }
        public string RSI_RELATIVE_STRENGTH_INDEX { get; set; }
        public string SMA_SIMPLE_MOVING_AVERAGE { get; set; }
        public string STOCHASTIC { get; set; }
        public string VBP_VOLUME_BY_PRICE { get; set; }
        public string VWAP_VOLUME_WEIGHTED_AVERAGE_PRICE { get; set; }
        public string WMA_WEIGHTED_MOVING_AVERAGE { get; set; }
        public string ZIG_ZAG { get; set; }
        public string AD_ACCUMULATION_DISTRIBUTION_SHORT { get; set; }
        public string ATR_AVERAGE_TRUE_RANGE_SHORT { get; set; }
        public string BOLLINGER_BANDS_SHORT { get; set; }
        public string CCI_COMMODITY_CHANNEL_INDEX_SHORT { get; set; }
        public string CMF_CHAIKIN_MONEY_FLOW_SHORT { get; set; }
        public string EMA_EXPONENTIAL_MOVING_AVERAGE_SHORT { get; set; }
        public string ICHIMOKU_KINKO_HYO_SHORT { get; set; }
        public string MACD_MOVING_AVERAGE_CONVERGENCE_DIVERGENCE_SHORT { get; set; }
        public string MFI_MONEY_FLOW_INDEX_SHORT { get; set; }
        public string MOMENTUM_SHORT { get; set; }
        public string PIVOT_POINTS_SHORT { get; set; }
        public string PRICE_ENVELOPES_SHORT { get; set; }
        public string PSAR_PARABOLIC_SAR_SHORT { get; set; }
        public string ROC_RATE_OF_CHANGE_SHORT { get; set; }
        public string RSI_RELATIVE_STRENGTH_INDEX_SHORT { get; set; }
        public string SMA_SIMPLE_MOVING_AVERAGE_SHORT { get; set; }
        public string STOCHASTIC_SHORT { get; set; }
        public string VBP_VOLUME_BY_PRICE_SHORT { get; set; }
        public string VWAP_VOLUME_WEIGHTED_AVERAGE_PRICE_SHORT { get; set; }
        public string WMA_WEIGHTED_MOVING_AVERAGE_SHORT { get; set; }
        public string ZIG_ZAG_SHORT { get; set; }
        public string PERIOD { get; set; }
        public string STANDARD_DEVIATION { get; set; }
        public string PERIOD_SENKOU_SPANB { get; set; }
        public string PERIOD_TENKAN { get; set; }
        public string SHORT_PERIOD { get; set; }
        public string LONG_PERIOD { get; set; }
        public string SIGNAL_PERIOD { get; set; }
        public string BOTTOM_BAND { get; set; }
        public string TOP_BAND { get; set; }
        public string DECIMALS { get; set; }
        public string INCREMENT { get; set; }
        public string INITIAL_ACCELERATION_FACTOR { get; set; }
        public string MAX_ACCELERATION_FACTOR { get; set; }
        public string DEVIATION { get; set; }
        public string HIGH_INDEX { get; set; }
        public string LOW_INDEX { get; set; }
        public string WITHDRAWAL_REQUEST { get; set; }
        public string OPEN_TRADE { get; set; }
        public string OPEN_PENDING_TRADE { get; set; }
        public string PENDING_TRADE_OPENED { get; set; }
        public string WITHDRAWAL_STATUS { get; set; }
        public string WITHDRAWAL_REQUEST_SENT { get; set; }
        public string BONUS { get; set; }
        public string CURRENCY { get; set; }
        public string LANGUAGES { get; set; }
        public string TEMPLATES { get; set; }
        public string THEMES { get; set; }
        public string TRADE_MARGIN_CLOSE { get; set; }
        public string TRADE_TP_CLOSE { get; set; }
        public string TRADE_SL_CLOSE { get; set; }
        public string TRAILING_SL_LIMIT { get; set; }
        public string TRAILING_TP_LIMIT { get; set; }
        public string EXPIRY_DATE { get; set; }
        public string ROLL_OVER_DATE { get; set; }
        public string TRADE_WILL_OPEN_ON_ASSET_OPEN { get; set; }
        public string INVALID_CLOSE_AMOUNT { get; set; }
        public string INVALID_REMINDING_AMOUNT { get; set; }
        public string TRADE_ID { get; set; }
        public string OLD_TRADE_ID { get; set; }
        public string NEW_TRADE_ID { get; set; }
        public string SEND { get; set; }
        public string LINK_FOR_RESET_PASSWORD_HAS_BEEN_SENT_TO_YOUR_EMAIL { get; set; }
        public string OLD_STATUS { get; set; }
        public string NEW_STATUS { get; set; }
        public string IN_PROCESS { get; set; }
        public string PASSWORD_IS_REQUIRED { get; set; }
        public string PASSWORD_MUST_BE_AT_LEAST_8_CHARACTERS_LONG { get; set; }
        public string PASSWORD_WAS_SUCCESSFULLY_CHANGED { get; set; }
        public string YOU_WILL_BE_REDIRECTED { get; set; }
        public string PASSWORD_WAS_NOT_CHANGED_CONTACT_SUPPORT { get; set; }
        public string SAVINGS_ACCOUNT { get; set; }
        public string TRANSFER_TO_SA { get; set; }
        public string TRANSFER_TO_BALANCE { get; set; }
        public string AVAILABLE_BALANCE { get; set; }
        public string TRANSFER_TO { get; set; }
        public string SA_BALANCE { get; set; }
        public string AMOUNT_CAN_NOT_BE_GREATER_THAN_BALANCE { get; set; }
        public string PERSONAL_INFORMATION_WAS_SAVED_SUCCESSFULLY { get; set; }
        public string FILE_UPLOADED { get; set; }
        public string DEPOSIT_WAS_ACCEPTED { get; set; }
        public string CLOSE_REASON { get; set; }
        public string CLOSE_TRADE { get; set; }
        public string PHONE_NUMBER_HAS_WRONG_FORMAT { get; set; }
        public string SOMETHING_HAPPEN_YOUR_BALANCE_WAS_NOT_INCREASE { get; set; }
        public string SEEMS_LIKE_YOU_STOP_THE_PROCESS_BEFORE_IT_END { get; set; }
        public string YOUR_DEPOSIT_HAS_BEEN_CREDITED_TO_YOUR_BALANCE { get; set; }
        public string YOUR_DEPOSIT_IS_ACTUALLY_IN_PROCESS_IT_CAN_TAKE_SEVERAL_TIME { get; set; }
        public string PLEASE_CONTACT_YOUR_AGENT { get; set; }
        public string THANK_YOU { get; set; }
        public string TRADE_WAS_CLOSED_SUCCESSFULLY { get; set; }
        public string TRADES_WERE_CLOSED_SUCCESSFULLY { get; set; }
        public string TP_SP_WAS_UPDATED { get; set; }
        public string PENDING_UPDATED { get; set; }
        public string EDIT_ALERT { get; set; }
        public string ASSET_PRICE_ALERT { get; set; }
        public string WERE_SORRY_WE_WERENT_ABLE_TO_FIND_ANYTHING_ABOUT_THIS_TOPIC { get; set; }
        public string VERIFICATION_FAILED_CONTACT_SUPPORT { get; set; }
        public string DEVICE_IS_NOT_VERIFIED { get; set; }
        public string DEVICE_IS_VERIFIED { get; set; }
        public string WAITING_FOR_VERIFICATION { get; set; }
        public string LINK_HAS_BEEN_SENT_TO_YOUR_EMAIL { get; set; }
        public string TRADE_NOT_CLOSED { get; set; }
        public string TRADES_NOT_CLOSED { get; set; }
        public string CONTACT_SUPPORT { get; set; }
        public string PASSWORD_WAS_NOT_CHANGED { get; set; }
        public string SELLER_CLOSED { get; set; }
        public string USER_CLOSED { get; set; }
        public string TIME_LIMIT_ENDED { get; set; }
        public string MARGIN_USAGE { get; set; }
        public string CANCELLED_BY_USER { get; set; }
        public string CANCELLED_BY_SELLER { get; set; }
        public string YOU_WILL_BE_REDIRECTED_TO_PSP { get; set; }
        public string REDIRECT_TO_DEPOSIT_PAGE { get; set; }
        public string PENDING_ORDER_CANCELLED { get; set; }
        public string ALL_ACTIVITIES { get; set; }
        public string PENDING_TRADE_CANCELLED { get; set; }
        public string OPEN_TRADE_PENDING { get; set; }
        public string DESCRIPTION { get; set; }
        public string SLTP_UPDATED { get; set; }
        public string TRADE_WAS_UPDATED_SUCCESSFULLY { get; set; }
        public string PENDING_TRADE_WAS_UPDATED { get; set; }
        public string TRADE_WILL_BE_EXECUTED_WHEN_MARKET_OPEN { get; set; }
        public string ASSET_IS_EXPIRED { get; set; }
        public string ASSET_CURRENTLY_CLOSED { get; set; }
        public string OPEN_TRADE_FAST_LOGIN { get; set; }
        public string SWITCH_TO_DEMO { get; set; }
        public string ASSET_EXPIRED { get; set; }
        public string ASSET_ROLLED_OVER { get; set; }
        public string SELECT_ASSET_CATEGORY { get; set; }
        public string PASSWORDS_DO_NOT_MATCH { get; set; }
        public string THE_PASSWORD_CAN_CONTAIN_ONLY_ENGLISH_LETTERS_NUMBERS_AND_THE_FOLLOWING_SYMBOLS { get; set; }
        public string PLEASE_CHECK_YOUR_INBOX_FOR_INSTRUCTIONS_ON_HOW_TO_COMPLETE_YOUR_REQUEST { get; set; }
        public string EMAIL_HAS_BEEN_SENT_TO { get; set; }
        public string NO_RECORDS_FOUND { get; set; }
        public string DEPOSIT_WITHDRAW_PNL_CLOSED_POSITIONS { get; set; }
        public string AVAILABLE_POSITIONS_MARGIN { get; set; }
        public string AMOUNT_AVAILABLE_FOR_TRADING { get; set; }
        public string SUM_CURRENT_OPEN_POSITIONS_PNL { get; set; }
        public string SUM_CURRENT_CLOSED_POSITIONS_PNL { get; set; }
        public string MINIMUM_EQUITY_YOU_MUST_HAVE_TO_KEEP_YOUR_OPEN_POSITIONS_RUNNING { get; set; }
        public string SIGN_DOD { get; set; }
        public string CONFIRM { get; set; }
        public string CLOSE_TRADE_CONFIRMATION { get; set; }
        public string YOU_ARE_ABOUT_TO_CLOSE { get; set; }
        public string TRADES_FOR_A_PNL_OF { get; set; }
        public string PLEASE_SIGN_DECLARATION_OF_DEPOSIT { get; set; }
        public string EXPIRE_DATE_IS_INVALID { get; set; }
        public string M_MARGIN_EQUITY_100 { get; set; }
        public string SAVE { get; set; }
        public string PASSWORD { get; set; }
        public string ADD_DEPOSIT { get; set; }

        [JsonProperty(NullValueHandling = NullValueHandling.Ignore)]
        public string ACTIVATE_PENDING_TRADE { get; set; }
        public string ADD_BONUS { get; set; }
        public string PLEASE_SIGN_THIS_DOCUMENT_IN_THE_BOX_BELOW { get; set; }
        public string PLEASE_APPROVE_TERMS_AND_CONDITIONS { get; set; }
        public string APPROVE { get; set; }
        public string COMPANY_DETAILS { get; set; }
        public string ANTI_PHISHING { get; set; }
        public string SET_SECRET_CODE { get; set; }
        public string ANTI_PHISHING_INFO { get; set; }
        public string ENTER_YOUR_SECRET_CODE_HERE { get; set; }
        public string COPY { get; set; }
        public string SEND_TO_EMAIL { get; set; }
        public string PRINT { get; set; }
        public string DECLINE { get; set; }
        public string PARTICIPANTS { get; set; }
        public string PIN_IS_REQUIRED { get; set; }
        public string PIN_SHOULD_BE_AT_LEAST_16_CHARACTERS { get; set; }
        public string PIN_SHOULD_BE_MAXIMUM_20_CHARACTERS { get; set; }
        public string REDEEM_VOUCHER { get; set; }
        public string EXPORT_ACTIVITIES { get; set; }
        public string EXPORT_FULL_ACTIVITIES_HISTORY { get; set; }
        public string EXPORT_NOT_ALLOWED { get; set; }
        public string CANCELED_BY_SELLER { get; set; }
        public string ACTIVITIES_DATA_DOES_NOT_EXISTS { get; set; }
        public string PENDING { get; set; }
        public string CHAT_DISABLED_FOR_YOUR_AGENT { get; set; }
        public string DOCUMENTS { get; set; }
        public string ERROR_GETTING_USER_DOCUMENTS { get; set; }
        public string SIGNED { get; set; }
        public string PENDING_SIGNATURE { get; set; }
        public string EMAIL_SENT { get; set; }
        public string SIGN { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public string DOCUMENT_LANG { get; set; }
        public string DOCUMENT_STATUS { get; set; }
        public string DOWNLOAD_DOCUMENT { get; set; }
        public string FAILED_DOWNLOAD_DOCUMENT { get; set; }
        public string PLEASE_SIGN_THIS_DOCUMENT_HERE { get; set; }
        public string CHARGEBACK { get; set; }
        public string REJECTED { get; set; }
        public string STOP_TRADE_FEES { get; set; }
        public string YOUR_TRADE_PNL_WILL_BE { get; set; }
        public string LIST_DISPLAY { get; set; }
        public string GRAPHS_DISPLAY { get; set; }
        public string SHOW_FAVORITES_LIST { get; set; }
        public string GRID_DISPLAY { get; set; }
        public string AREA_PLOT { get; set; }
        public string LINE_PLOT { get; set; }
        public string CANDLESTICK_PLOT { get; set; }
        public string BAR_PLOT { get; set; }
        public string CHANGE_BACKGROUND { get; set; }
        public string TECHNICAL_INDICATORS { get; set; }
        public string TOTAL_PNL { get; set; }
        public string CHOOSE_YOUR_PNL_MULTIPLIER { get; set; }
        public string CHOOSE_YOUR_TIME_LIMIT { get; set; }
        public string MIN_AVAILABLE_REQUIRED { get; set; }
        public string INSUFFICIENT_AVAILABLE_FUNDS { get; set; }
        public string INSUFFICIENT_FUNDS_FOR_MULTIPLIER { get; set; }
        public string STOP { get; set; }
        public string CONFIRM_TRADE { get; set; }
        public string TRADE_CONFIRMATION { get; set; }
        public string YOU_ARE_ABOUT_TO_OPEN_A_TRADE { get; set; }
        public string YOU_DONT_HAVE_ENOUGH_MONEY_FOR_THIS_TRADE { get; set; }
        public string POSITION { get; set; }
        public string ASSET { get; set; }
        public string CLOSE_RATE { get; set; }
        public string BOOST { get; set; }
        public string TIME { get; set; }
        public string FROM_CHRONO_TO_TRADE { get; set; }
        public string TRADE_VALUE { get; set; }
        public string LIGHT_MODE { get; set; }
        public string DARK_MODE { get; set; }
        public string ASSET_IS_NOT_AVAILABLE_FOR_TRADE_RIGHT_NOW_PLEASE_TRY_AGAIN_LATER { get; set; }
        public string FAILED_TO_INITIALIZE_TRADING { get; set; }
        public string SYSTEM { get; set; }
        public string CHRONO { get; set; }
        public string REGULAR { get; set; }
        public string CLOSE_TRAILING_SL_LIMIT { get; set; }
        public string CLOSE_TRAILING_TP_LIMIT { get; set; }
        public string CLOSE_TRADE_TP_CLOSE { get; set; }
        public string CLOSE_TRADE_SL_CLOSE { get; set; }
        public string GENERAL_DOD { get; set; }
        public string TOTAL_INVESTMENT { get; set; }
        public string WIN_PERCENTAGE { get; set; }
        public string BANKING { get; set; }
        public string TRADING { get; set; }
        public string TOTAL { get; set; }
        public string TRADES { get; set; }
        public string BEST_TRADE_RETURN { get; set; }
        public string RETURN { get; set; }
        public string ACCOUNT { get; set; }
        public string AV_MONTH { get; set; }
        public string ROI { get; set; }
        public string LONGEST_TRADE_DURATION { get; set; }
        public string AVERAGE_TRADE_DURATION { get; set; }
        public string MARKET { get; set; }
        public string LIMIT { get; set; }
        public string ENTRY_PRICE { get; set; }
        public string TOTAL_LOWER_CASE { get; set; }
        public string FAILED_TO_RETRIEVE_REQUESTED_DOCUMENT { get; set; }
        public string CLIENT_BLOCK_STATUS { get; set; }
        public string THIS_ACCOUNT_IS_BLOCKED_DOU_TO_SUS_ACTIVITY { get; set; }
        public string YOUR_ORDER_WILL_BE_FILLED_ONCE_MARKET_WILL_OPEN { get; set; }
        public string COMPLIANCE_STATUS { get; set; }
        public string SAVING_ACCOUNT { get; set; }
    }

    public class LanguageData
    {
        public string _id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string platform { get; set; }
        public bool active { get; set; }
        public bool _default { get; set; }
    }
}


