// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Usage", "CA2208:Instantiate argument exceptions correctly", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Api.Crm.Settings.PlatformTabApi.ParseMailToKeyValuePair(AirSoftAutomationFramework.Objects.DTOs.Email)~System.Collections.Generic.Dictionary{System.String,System.String}")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Api.Crm.AccountsApi.UsersMenuApi.UserMenuApi.UserApi.#ctor(AirSoftAutomationFramework.Internals.Factory.IApplicationFactory,OpenQA.Selenium.IWebDriver,AirSoftAutomationFramework.Internals.DAL.ApiAccess.IApiAccess,AirSoftAutomationFramework.Internals.DAL.MongoDb.IMongoDbAccess)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Api.Crm.AccountsApi.UsersMenuApi.UserMenuApi.UserApi.GetAllowedFingerPrintFromMongo(System.String)~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Api.Crm.AccountsApi.UsersMenuApi.UserMenuApi.UserApi.GetPendingFingerPrintFromMongo(System.String)~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.#ctor(AirSoftAutomationFramework.Internals.Factory.IApplicationFactory,OpenQA.Selenium.IWebDriver)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.ClickOnSendApiKeyBtn~AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.IUserUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.GetApiKey~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.GetGeneratedApiKeyBodyPopup~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.SendApiKey(System.String)~AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.IUserUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.SetAllowedIpAddresses(System.String[])~AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.IUserUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.SetApiKey(System.String)~AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.IUserUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.UserUi.SetExtention(System.String)~AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi.IUserUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:AirSoftAutomationFramework.Objects.ForexObjects.Api.Crm.AccountsApi.UsersMenuApi.UserMenuApi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:AirSoftAutomationFramework.Objects.ForexObjects.Ui.Crm.Accounts.UsersMenuUi")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.delete_erp_user_id")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.delete_erp_user_username")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.erp_user_id_assigned")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.erp_username")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.kyc_credit_debit_card_documentation_status")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.kyc_proof_of_identity_status")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.kyc_proof_of_residency_status")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.manual_erp_user_id")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~P:AirSoftAutomationFramework.Objects.DTOs.GetFinanceDataResponse.FinanceData.psp_transaction_id")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.TradingPlatform.TradeObjects.TradeApi.Settings.SavingAccountTpApi.#ctor(AirSoftAutomationFramework.Internals.Factory.IApplicationFactory,OpenQA.Selenium.IWebDriver,AirSoftAutomationFramework.Internals.DAL.ApiAccess.IApiAccess)")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.TradingPlatform.TradeObjects.TradeApi.Settings.SavingAccountTpApi.PostTransferToBalanceFromTpRequest(System.String,System.String,System.Int32,AirSoftAutomationFramework.Objects.DTOs.GetLoginResponse,System.Boolean)~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "member", Target = "~M:AirSoftAutomationFramework.Objects.ForexObjects.TradingPlatform.TradeObjects.TradeApi.Settings.SavingAccountTpApi.PostTransferToSavingAccountFromTpRequest(System.String,System.String,System.Int32,AirSoftAutomationFramework.Objects.DTOs.GetLoginResponse,System.Boolean)~System.String")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "namespace", Target = "~N:AirSoftAutomationFramework.Objects.ForexObjects.TradingPlatform.TradeObjects.TradeApi.Settings")]
[assembly: SuppressMessage("Naming", "VSSpell001:Spell Check", Justification = "<Pending>", Scope = "type", Target = "~T:AirSoftAutomationFramework.Objects.ForexObjects.TradingPlatform.TradeObjects.TradeApi.Settings.SavingAccountTpApi")]
