namespace AirSoftAutomationFramework.Objects.DTOs
{
    public class ErpLanguage
    {
        public string _id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public string platform { get; set; }
        public Translations translations { get; set; }
        public bool active { get; set; }
        public bool @default { get; set; }
    }
    
    public class Translations
    {
        public string PENDING { get; set; }
        public string DASHBOARD { get; set; }
        public string CRM { get; set; }
        public string LEADS { get; set; }
        public string ATTRIBUTION { get; set; }
        public string CUSTOMERS { get; set; }
        public string BANKING { get; set; }
        public string SALES { get; set; }
        public string PLANNING { get; set; }
        public string REPORTS { get; set; }
        public string CFD { get; set; }
        public string ASSETS_ON_FRONT { get; set; }
        public string GROUPS { get; set; }
        public string TRADE_ID { get; set; }
        public string OPEN_TRADES { get; set; }
        public string REOPEN_TRADE { get; set; }
        public string PENDING_TRADES { get; set; }
        public string PENDING_TRADE_CANCELLED { get; set; }
        public string CLOSED_TRADES { get; set; }
        public string TRADES { get; set; }
        public string PNL { get; set; }
        public string WORTH { get; set; }
        public string IN { get; set; }
        public string RISK { get; set; }
        public string CAMPAIGN { get; set; }
        public string HOME { get; set; }
        public string CAMPAIGNS { get; set; }
        public string YOUR_IP_IS { get; set; }
        public string EXTERNAL_SOURCE { get; set; }
        public string ONGOING_TRADES { get; set; }
        public string EXPIRED_TRADES { get; set; }
        public string RISK_TOOLS { get; set; }
        public string RISK_PLANNING { get; set; }
        public string ASSETS { get; set; }
        public string ONE_TOUCHES { get; set; }
        public string SNAPSHOTS { get; set; }
        public string ACCOUNTS { get; set; }
        public string ROLES { get; set; }
        public string USERS { get; set; }
        public string USER { get; set; }
        public string MAIL { get; set; }
        public string INBOX { get; set; }
        public string COMPOSE_MAIL { get; set; }
        public string SINGLE_MAIL { get; set; }
        public string FORM_STUFF { get; set; }
        public string COMMON_ELEMENTS { get; set; }
        public string VALIDATION_ELEMENTS { get; set; }
        public string FORM_WIZARD { get; set; }
        public string FILE_UPLOAD { get; set; }
        public string IMAGE_CROP { get; set; }
        public string UI_KIT { get; set; }
        public string GENERAL_ELEMENTS { get; set; }
        public string GENERAL_SETTINGS { get; set; }
        public string WITHDRAWAL_BY_WALLET { get; set; }
        public string BLOCK_EDIT_PROFILE { get; set; }
        public string ALERT { get; set; }
        public string SHOW_CLOSED_PNL { get; set; }
        public string CLIENT_EXPORT_ACTIVITY { get; set; }
        public string BUTTONS_ICONS { get; set; }
        public string TYPOGRAPHY { get; set; }
        public string NAVIGATION_ACCORDIONS { get; set; }
        public string MODALS { get; set; }
        public string TILES { get; set; }
        public string PORTLETS { get; set; }
        public string GRID { get; set; }
        public string WIDGETS { get; set; }
        public string TREE { get; set; }
        public string LISTS { get; set; }
        public string ALERTS_NOTIFICATIONS { get; set; }
        public string MATERIAL_UI { get; set; }
        public string SHOP { get; set; }
        public string ORDERS { get; set; }
        public string SINGLE_ORDER { get; set; }
        public string PRODUCTS { get; set; }
        public string SINGLE_PRODUCT { get; set; }
        public string INVOICES { get; set; }
        public string SINGLE_INVOICE { get; set; }
        public string TABLES { get; set; }
        public string BOOTSTRAP_TABLES { get; set; }
        public string DATATABLES { get; set; }
        public string UI_GRID { get; set; }
        public string NGTABLE { get; set; }
        public string SMARTTABLE { get; set; }
        public string FOOTABLE { get; set; }
        public string EXTRA_PAGES { get; set; }
        public string LOGIN_PAGE { get; set; }
        public string SIGNUP_PAGE { get; set; }
        public string FORGOT_PASSWORD_PAGE { get; set; }
        public string FORGOT_PASSWORD { get; set; }
        public string PAGE_404 { get; set; }
        public string PAGE_500 { get; set; }
        public string PAGE_OFFLINE { get; set; }
        public string LOCKED_SCREEN { get; set; }
        public string GALLERY { get; set; }
        public string TIMELINE { get; set; }
        public string CHAT { get; set; }
        public string CHAT_CONNECTION_UNAVAILABLE { get; set; }
        public string PBX { get; set; }
        public string SEARCH_RESULTS { get; set; }
        public string PROFILE_PAGE { get; set; }
        public string LAYOUTS { get; set; }
        public string BOXED_LAYOUT { get; set; }
        public string BASE_LAYOUT { get; set; }
        public string EXPANDED_SIDEBAR { get; set; }
        public string SMALL_HEADER { get; set; }
        public string NON_FIXED_HEADER { get; set; }
        public string NON_FIXED_SIDEBAR { get; set; }
        public string HEADER_WITH_CONTENT { get; set; }
        public string HORIZONTAL_MENU { get; set; }
        public string RTL_LAYOUT { get; set; }
        public string FRONT_THEMES { get; set; }
        public string CORPORATE { get; set; }
        public string COMMERCE { get; set; }
        public string MAPS { get; set; }
        public string VECTOR_MAPS { get; set; }
        public string GOOGLE_MAPS { get; set; }
        public string LEAFLET_MAPS { get; set; }
        public string CALENDAR { get; set; }
        public string CHARTS_GRAPHS { get; set; }
        public string MENU_LEVELS { get; set; }
        public string MENU_LEVEL { get; set; }
        public string DOCUMENTATION { get; set; }
        public string MASONRY { get; set; }
        public string INTRO { get; set; }
        public string DRAGULA { get; set; }
        public string CREATE_ROLE { get; set; }
        public string ID { get; set; }
        public string ACTION { get; set; }
        public string EDIT { get; set; }
        public string DELETE { get; set; }
        public string COLOR { get; set; }
        public string SAVE { get; set; }
        public string LOAD { get; set; }
        public string COMMENTS { get; set; }
        public string COMMENT { get; set; }
        public string ADD_COMMENT { get; set; }
        public string ADD_COMMENT_EVENT { get; set; }
        public string CREATE_COMMENT { get; set; }
        public string DELETED_COMMENT { get; set; }
        public string COMMENT_ID { get; set; }
        public string CUSTOMER_IS_REQUIRED { get; set; }
        public string ADD { get; set; }
        public string SEND { get; set; }
        public string TIME { get; set; }
        public string TODAY { get; set; }
        public string YESTERDAY { get; set; }
        public string WEEK { get; set; }
        public string MONTH { get; set; }
        public string YEAR { get; set; }
        public string THIS { get; set; }
        public string PREVIOUS { get; set; }
        public string ALL { get; set; }
        public string EVENTS { get; set; }
        public string CREATE_LEAD { get; set; }
        public string CREATE_CLIENT { get; set; }
        public string IMPORT_LEAD { get; set; }
        public string IMPORT_CLIENT { get; set; }
        public string IMPORT_ROLE { get; set; }
        public string CHOOSE_ROLE_TO_IMPORT { get; set; }
        public string IMPORT { get; set; }
        public string INFO { get; set; }
        public string PERMISSIONS { get; set; }
        public string NOTIFICATIONS { get; set; }
        public string SUBROLES { get; set; }
        public string SELECT_ROLE_TYPE { get; set; }
        public string ROLE_NAME_REQUIRED { get; set; }
        public string AFFILIATE { get; set; }
        public string USERS_ONLY { get; set; }
        public string DIALER_API { get; set; }
        public string SINGLE_OFFICE { get; set; }
        public string SHOW_ROLE { get; set; }
        public string VIEW_ONLY { get; set; }
        public string VIEW_EDIT { get; set; }
        public string SUBMIT { get; set; }
        public string CREATE_USER { get; set; }
        public string CREATE_AFFILIATE { get; set; }
        public string CHOOSE_ROLE { get; set; }
        public string CREATE_EDIT_ROLE { get; set; }
        public string ALL_ROLES { get; set; }
        public string FIRST_NAME { get; set; }
        public string LAST_NAME { get; set; }
        public string USERNAME { get; set; }
        public string EMAIL { get; set; }
        public string ROLE { get; set; }
        public string MANAGEMENT { get; set; }
        public string CLIENT_ID { get; set; }
        public string CLIENT_NAME { get; set; }
        public string CLIENT_FULL_NAME { get; set; }
        public string TIME_START { get; set; }
        public string TYPE { get; set; }
        public string ASSET { get; set; }
        public string AMOUNT { get; set; }
        public string TO { get; set; }
        public string YOU_ARE_ABOUT_TO_ASSIGN { get; set; }
        public string CLIENT_S { get; set; }
        public string OPEN_PRICE { get; set; }
        public string CURRENT_PRICE { get; set; }
        public string OPEN_PNL { get; set; }
        public string CLOSE_PNL { get; set; }
        public string M_MARGIN { get; set; }
        public string MARGIN_USAGE { get; set; }
        public string PNL_REAL_TITLE { get; set; }
        public string PNL_BONUS_TITLE { get; set; }
        public string OPEN_PNL_TITLE { get; set; }
        public string BALANCE_TITLE { get; set; }
        public string EQUITY_TITLE { get; set; }
        public string AVAILABLE_TITLE { get; set; }
        public string PNL_TITLE { get; set; }
        public string SUM_CURRENT_CLOSED_POSITIONS_PNL { get; set; }
        public string M_MARGIN_TITLE { get; set; }
        public string PLEASE_SIGN_DECLARATION_OF_DEPOSIT { get; set; }
        public string EXPIRE_DATE_IS_INVALID { get; set; }
        public string M_MARGIN_USAGE_TITLE { get; set; }
        public string TITLE { get; set; }
        public string SL_TP { get; set; }
        public string COMMISSION { get; set; }
        public string ORDER_ID { get; set; }
        public string SWAP { get; set; }
        public string SUB_USERS { get; set; }
        public string PHONE { get; set; }
        public string YOUR_STATUS { get; set; }
        public string ACTIVE { get; set; }
        public string ADD_AS_CHILD { get; set; }
        public string OFFICE { get; set; }
        public string CHOOSE_OFFICE { get; set; }
        public string IP_ADDRESS { get; set; }
        public string COUNTRY { get; set; }
        public string CHOOSE_COUNTRY { get; set; }
        public string CHOOSE_CURRENCY { get; set; }
        public string CHOOSE_CAMPAIGN { get; set; }
        public string GMT_TIME_ZONE { get; set; }
        public string SALE_TYPE { get; set; }
        public string EXTENSION { get; set; }
        public string PBX_TYPE { get; set; }
        public string FTD { get; set; }
        public string RETENTION { get; set; }
        public string PASSWORD { get; set; }
        public string CONFIRM { get; set; }
        public string EDIT_USER { get; set; }
        public string LAST_NAME_IS_REQUIRED { get; set; }
        public string LAST_NAME_MUST_BE_AT_LEAST_2_CHARACTERS { get; set; }
        public string FIRST_NAME_IS_REQUIRED { get; set; }
        public string FIRST_NAME_MUST_BE_AT_LEAST_2_CHARACTERS { get; set; }
        public string LAST_NAME_MUST_BE_MAXIMUM_30_CHARACTERS { get; set; }
        public string USERNAME_IS_REQUIRED { get; set; }
        public string USERNAME_MUST_BE_AT_LEAST_2_CHARACTERS { get; set; }
        public string EMAIL_IS_REQUIRED { get; set; }
        public string EMAIL_HAS_TO_BE_IN_THE_RIGHT_FORMAT { get; set; }
        public string EMAIL_HAS_BEEN_SENT { get; set; }
        public string EMAIL_FAILED { get; set; }
        public string PHONE_IS_REQUIRED { get; set; }
        public string OFFICE_IS_REQUIRED { get; set; }
        public string GMT_TIME_IS_REQUIRED { get; set; }
        public string WORKING_HOURS { get; set; }
        public string SEND_ALERT_TO { get; set; }
        public string ROLE_IS_REQUIRED { get; set; }
        public string COMMENT_IS_REQUIRED { get; set; }
        public string UPLOAD_FILE { get; set; }
        public string UPLOAD { get; set; }
        public string IMPORT_INSTRUCTIONS { get; set; }
        public string DOWNLOAD_EXAMPLE_FILE { get; set; }
        public string CHOOSE_FILE { get; set; }
        public string SHOW_DEPOSITS_AMOUNT { get; set; }
        public string CHECK_YOUR_FILE_THERE_ARE_SOME_ERRORS { get; set; }
        public string ROW { get; set; }
        public string BLOCK_USER { get; set; }
        public string LEADS_WERE_SUCCESSFULLY_IMPORTED { get; set; }
        public string EXCEL_FILE_STRUCTURE { get; set; }
        public string TIME_ZONE { get; set; }
        public string CURRENCIES { get; set; }
        public string SALES_TYPE { get; set; }
        public string ROLE_NAME { get; set; }
        public string ADD_GROUPS { get; set; }
        public string DEFAULT { get; set; }
        public string DUPLICATE { get; set; }
        public string OK { get; set; }
        public string CANCEL { get; set; }
        public string EDIT_GROUP { get; set; }
        public string DEFAULT_SETTINGS_FOR_GROUP { get; set; }
        public string SWAP_TIME { get; set; }
        public string GMT { get; set; }
        public string SHOW_FTD_AMOUNT { get; set; }
        public string SWAP_LONG { get; set; }
        public string SWAP_SHORT { get; set; }
        public string SPREAD { get; set; }
        public string MINIMUM_STEP { get; set; }
        public string MINIMUM_AMOUNT { get; set; }
        public string LEVERAGE { get; set; }
        public string SHOW_ALL_DEPOSITS { get; set; }
        public string SHOW_SALES_STATUS { get; set; }
        public string SHOW_DEPOSIT_DATE { get; set; }
        public string SHOW_CLIENT_EMAIL { get; set; }
        public string SHOW_CLIENT_PHONE { get; set; }
        public string MAINTENANCE_MARGIN_LEVERAGE { get; set; }
        public string DEFAULT_SETTINGS_FOR_GROUP_TYPES { get; set; }
        public string SETTINGS_FOR_SPECIFIC_ASSETS { get; set; }
        public string ADD_ASSET { get; set; }
        public string SELECT_ASSET { get; set; }
        public string EDIT_ASSET_TYPE { get; set; }
        public string SWAP_TIME_MUST_BE_IN_FORMAT { get; set; }
        public string MAINTANCE_MARGIN { get; set; }
        public string TAKE_PROFIT { get; set; }
        public string STOP_LOSS { get; set; }
        public string AUTO_LOGIN_LINK { get; set; }
        public string CURRENCY { get; set; }
        public string ENTER_YOUR_PASSWORD { get; set; }
        public string PLEASE_LOG_IN { get; set; }
        public string KNOW_YOUR_PASSWORD { get; set; }
        public string CUSTOMIZE { get; set; }
        public string SOLID { get; set; }
        public string GRADIENT { get; set; }
        public string PRIMARY_COLOR { get; set; }
        public string NAVIGATION { get; set; }
        public string TOGGLE_HEADER { get; set; }
        public string TOGGLE_NAVIGATION { get; set; }
        public string MINOTAUR_NOTIFICATIONS { get; set; }
        public string EDIT_PROFILE { get; set; }
        public string TASKS { get; set; }
        public string SETTINGS { get; set; }
        public string LOGOUT { get; set; }
        public string LOCK { get; set; }
        public string LANGUAGE { get; set; }
        public string ENGLISH { get; set; }
        public string SLOVAK { get; set; }
        public string CZECH { get; set; }
        public string GERMAN { get; set; }
        public string TOGGLE_RIGHTBAR { get; set; }
        public string ERROR_404 { get; set; }
        public string SOMETHING_NOT_RIGHT_HERE { get; set; }
        public string THE_PAGE_YOU_ARE_LOOKING_FOR_CANNOT_BE_FOUND { get; set; }
        public string TRY_AGAIN { get; set; }
        public string RETURN_TO_HOME { get; set; }
        public string CLIENTS_PROFILE { get; set; }
        public string FAST_LOGIN { get; set; }
        public string CLIENT_INFORMATION { get; set; }
        public string YOUR_NOTE { get; set; }
        public string FULL_NAME { get; set; }
        public string SALES_STATUS { get; set; }
        public string KYC_STATUS { get; set; }
        public string ACCOUNT_SETTINGS { get; set; }
        public string SALES_AGENT { get; set; }
        public string CFD_GROUP { get; set; }
        public string BINARY_RISK { get; set; }
        public string COMPLIANCE_STATUS { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public string LOG_OUT { get; set; }
        public string TOTAL { get; set; }
        public string ORIGINAL { get; set; }
        public string GLOBAL { get; set; }
        public string GENERAL { get; set; }
        public string OFFICES { get; set; }
        public string BINARY { get; set; }
        public string CRYPTO { get; set; }
        public string SUPERADMIN { get; set; }
        public string ACTIVE_SYSTEM { get; set; }
        public string CHRONO { get; set; }
        public string CHRONO_ONLY { get; set; }
        public string TRADING_PLATFORMS { get; set; }
        public string LANGUAGES { get; set; }
        public string CREATE_LANGUAGE { get; set; }
        public string EDIT_LANGUAGE { get; set; }
        public string DELETE_LANGUAGE { get; set; }
        public string CODE { get; set; }
        public string IMAGE { get; set; }
        public string SELECT_IMAGE { get; set; }
        public string TRADING_PLATFORM { get; set; }
        public string BACK_OFFICE { get; set; }
        public string EMAIL_SETTINGS { get; set; }
        public string API { get; set; }
        public string API_IS_NOT_ALLOWED_TO_BE_EMPTY_WHEN_TYPE_IS_SENDGRID { get; set; }
        public string FROM_EMAIL { get; set; }
        public string SMTP_HOST { get; set; }
        public string SMTP_PORT { get; set; }
        public string SMTP_SECURE { get; set; }
        public string SMTP_AUTH { get; set; }
        public string SMTP_USERNAME { get; set; }
        public string SMTP_PASSWORD { get; set; }
        public string INITIAL_BONUS { get; set; }
        public string AFTER_DEPOSIT_BONUS { get; set; }
        public string BONUS_ON_DEPOSIT { get; set; }
        public string CURRENCIES_ACCEPTED { get; set; }
        public string PERCENT_FROM_DEPOSIT { get; set; }
        public string BRAND_RESTRICTION { get; set; }
        public string BRAND_PERMISSIONS { get; set; }
        public string CLOSE { get; set; }
        public string DEFAULT_CURRENCY { get; set; }
        public string MARK_AS_DEFAULT { get; set; }
        public string PLEASE_CHOOSE_AT_LEAST_ONE_DEFAULT_CURRENCY { get; set; }
        public string URL { get; set; }
        public string DEPOSIT_RANGE { get; set; }
        public string CREATE_DEPOSIT_RANGE_GROUP { get; set; }
        public string EDIT_DEPOSIT_RANGE_GROUP { get; set; }
        public string FROM_SUM { get; set; }
        public string TO_SUM { get; set; }
        public string TRADE_VOL { get; set; }
        public string BONUS_ON_TRADE_VOL_ { get; set; }
        public string BONUS_ON_FTD { get; set; }
        public string ACCOUNT_TYPES { get; set; }
        public string REOPEN { get; set; }
        public string EDIT_ACCOUNT_TYPE_MENU { get; set; }
        public string CREATE_ACCOUNT_TYPE_MENU { get; set; }
        public string SHOW_ON_REGISTER { get; set; }
        public string CHRONO_TRADING { get; set; }
        public string ENABLE_DEMO { get; set; }
        public string DEMO_INITIAL_DEMO { get; set; }
        public string DEMO_REINITIALIZE_BALANCE_ON_0 { get; set; }
        public string TRAIDING_TABS { get; set; }
        public string SAVING_ACCOUNT { get; set; }
        public string CREATE_SAVING_ACCOUNT_GROUP { get; set; }
        public string EDIT_SAVING_ACCOUNT_GROUP { get; set; }
        public string PERCENT_PER_MONTH { get; set; }
        public string CLIENT_TRANSFER { get; set; }
        public string DAILY { get; set; }
        public string TRADING { get; set; }
        public string TABS { get; set; }
        public string EDIT_TAB_MENU { get; set; }
        public string CREATE_TAB_MENU { get; set; }
        public string PLEASE_FILL_TAB_CONTENT { get; set; }
        public string CONTENT { get; set; }
        public string CITY { get; set; }
        public string CREATE { get; set; }
        public string CREATE_NEW_OFFICE { get; set; }
        public string IP_INTERNET { get; set; }
        public string ASSIGN_IP { get; set; }
        public string ASSIGN_TZ { get; set; }
        public string DO_YOU_WANT_TO_ADD_OR_OVERRIDE_THIS_IP { get; set; }
        public string OVERRIDE { get; set; }
        public string USERNAME_MUST_BE_AN_EMAIL { get; set; }
        public string USERNAME_MUST_BE_AT_LEAST_3_CHARACTERS { get; set; }
        public string USERNAME_REQUIRED { get; set; }
        public string PASSWORD_MUST_BE_AT_LEAST_10_CHARACTERS_LONG { get; set; }
        public string PASSWORD_IS_REQUIRED { get; set; }
        public string RESET_PASSWORD { get; set; }
        public string _2_WAY_VERIFICATION { get; set; }
        public string ALERT_PRICES { get; set; }
        public string TRADE_SL_CLOSE { get; set; }
        public string TRADE_TP_CLOSE { get; set; }
        public string TRADE_MARGIN_CLOSE { get; set; }
        public string TRADE_ORDER_ACTIVATED { get; set; }
        public string CLIENT_NEW_BONUS { get; set; }
        public string WALLET_PSP { get; set; }
        public string BANK_PSP { get; set; }
        public string CLIENT_DEPOSIT { get; set; }
        public string WITHDRAWAL_REQUEST { get; set; }
        public string WITHDRAWAL_SUSPENDED { get; set; }
        public string FORGET_PASSWORD { get; set; }
        public string CLIENT_REGISTER { get; set; }
        public string FIRST_DEPOSIT { get; set; }
        public string TRIAL_ABOUT_TO_END { get; set; }
        public string TRIAL_ENDED { get; set; }
        public string CLIENT_ACCOUNT_ACTIVE { get; set; }
        public string API_DOCS_LINK { get; set; }
        public string PSP_REDIRECT_LINK { get; set; }
        public string MARGIN_CALL_ERP { get; set; }
        public string MARGIN_CALL_TRADE { get; set; }
        public string TRAILING_TP_LIMIT { get; set; }
        public string TRAILING_SL_LIMIT { get; set; }
        public string OUTSIDE_WORKING_HOURS { get; set; }
        public string NEW_CLIENT_SET_PASSWORD { get; set; }
        public string LOGIN { get; set; }
        public string CUSTOMER { get; set; }
        public string PHONE_NUMBER { get; set; }
        public string E_MAIL { get; set; }
        public string SALE_STATUS_TEXT { get; set; }
        public string PLANNING_A_MEETING { get; set; }
        public string LOCAL_TIME { get; set; }
        public string GMT_TIME { get; set; }
        public string CUSTOMER_TIME { get; set; }
        public string NO_EVENTS { get; set; }
        public string MORE { get; set; }
        public string ADD_NEW_EVENT { get; set; }
        public string PNL_BONUS { get; set; }
        public string REAL { get; set; }
        public string PNL_REAL { get; set; }
        public string BALANCE { get; set; }
        public string DEMO_BALANCE { get; set; }
        public string INFORMATION { get; set; }
        public string ADD_TAB { get; set; }
        public string SHOW_SELLER { get; set; }
        public string SHOW_MANAGER { get; set; }
        public string SHOW_OFFICE { get; set; }
        public string TOTAL_DEPOSIT { get; set; }
        public string TOTAL_PNL { get; set; }
        public string DEPOSIT { get; set; }
        public string DEPOSITS { get; set; }
        public string WITHDRAWALS { get; set; }
        public string WITHDRAWAL { get; set; }
        public string CHARGEBACKS { get; set; }
        public string CHARGEBACK { get; set; }
        public string TOTAL_VOLUME { get; set; }
        public string TOTAL_DEPOSIT_PER_CURRENCY { get; set; }
        public string CALCULATE { get; set; }
        public string SALARY_CALCULATOR { get; set; }
        public string START_SEARCHING { get; set; }
        public string NO_DATA_IS_AVAILABLE { get; set; }
        public string CREATE_CAMPAIGN { get; set; }
        public string PROFIT { get; set; }
        public string COST { get; set; }
        public string PLAYER_VALUE { get; set; }
        public string AFFILIATE_NAME { get; set; }
        public string CHOOSE_AFFILIATE_NAME { get; set; }
        public string DEAL { get; set; }
        public string CHOOSE_DEAL { get; set; }
        public string CAMPAIGN_CODE { get; set; }
        public string GENERATE { get; set; }
        public string CAMPAIGN_NAME { get; set; }
        public string MINIMAL_DEPOSIT { get; set; }
        public string COUNTRY_BLOCKED { get; set; }
        public string ACCOUNT_TYPE { get; set; }
        public string CHOOSE_ACCOUNT_TYPE { get; set; }
        public string AFFILIATE_MANAGER { get; set; }
        public string CHOOSE_AFFILIATE_MANAGER { get; set; }
        public string ACTIVE_CAMPAIGN { get; set; }
        public string INACTIVE_CAMPAIGN { get; set; }
        public string API_KEY { get; set; }
        public string CREATION_DATE { get; set; }
        public string PIXEL { get; set; }
        public string REGISTER_PIXEL { get; set; }
        public string DEPOSIT_PIXEL { get; set; }
        public string DEPOSIT_STATISTICS { get; set; }
        public string DEPOSIT_PER_CURRENCY { get; set; }
        public string CAMPAIGN_COST { get; set; }
        public string CAMPAIGN_STATISTIC { get; set; }
        public string EDIT_CAMPAIGN { get; set; }
        public string CHOOSE { get; set; }
        public string CHOOSE_STATUS { get; set; }
        public string CHOOSE_FILTER { get; set; }
        public string LABEL { get; set; }
        public string FROND_ORDERS { get; set; }
        public string ADD_GROUP { get; set; }
        public string HIDE_ASSETS_IN_FRONT { get; set; }
        public string PIXEL_GRAF { get; set; }
        public string CONVERSION { get; set; }
        public string SECURITY { get; set; }
        public string BLOCKED_USERS { get; set; }
        public string BLOCKED_IPS { get; set; }
        public string ADD_PAYMENT_GATEWAY { get; set; }
        public string EDIT_PAYMENT_GATEWAY { get; set; }
        public string ENTER_NEW_GROUP_NAME { get; set; }
        public string SAVE_AND_CLOSE { get; set; }
        public string CHOOSE_PSP { get; set; }
        public string CREATE_PSP { get; set; }
        public string CREATE_PAYMENT_GATEWAY { get; set; }
        public string DISPLAY_NAME { get; set; }
        public string FREE_TEXT { get; set; }
        public string LOGO { get; set; }
        public string TEST_MODE { get; set; }
        public string HIDE_MIN_DEPOSIT { get; set; }
        public string SHOW_IN_IFRAME { get; set; }
        public string HAVE_DOD { get; set; }
        public string ENABLED { get; set; }
        public string COUNTRIES { get; set; }
        public string MERCHANT_ID { get; set; }
        public string MERCHANT_PASSWORD { get; set; }
        public string ORDER_DESCRIPTION { get; set; }
        public string DEFAULT_AMOUNT { get; set; }
        public string CONVERT_TO { get; set; }
        public string ADD_EMAIL { get; set; }
        public string CREATE_EMAIL { get; set; }
        public string EMAIL_TYPE { get; set; }
        public string CHOOSE_EMAIL_TYPE { get; set; }
        public string CHOOSE_LANGUAGE { get; set; }
        public string EMAIL_SUBJECT { get; set; }
        public string EMAIL_BODY { get; set; }
        public string GLOBAL_VARIABLES { get; set; }
        public string SEND_BY { get; set; }
        public string DEPOSIT_TYPE { get; set; }
        public string ON_TRADING_PLATFORM { get; set; }
        public string BY_EMAIL { get; set; }
        public string TEMPLATE_VARIABLES { get; set; }
        public string SELLER_EMAILS_TEMPLATES { get; set; }
        public string EMAIL_NAME { get; set; }
        public string TEMPLATE { get; set; }
        public string CHOOSE_TEMPLATE { get; set; }
        public string NEW_TEMPLATE { get; set; }
        public string SAVE_AND_SEND { get; set; }
        public string PROOF_OF_IDENTITY { get; set; }
        public string PROOF_OF_RESIDENCY { get; set; }
        public string CARD_DOCUMENTATION { get; set; }
        public string CARD_BACK_DOCUMENTATION { get; set; }
        public string DETAILS_FOR_CLIENT { get; set; }
        public string GENERAL_KYC { get; set; }
        public string NOTE_FOR_CLIENT { get; set; }
        public string NOTE { get; set; }
        public string TRADING_VOLUME { get; set; }
        public string ALL_TRADES { get; set; }
        public string FINANCES { get; set; }
        public string WITHDRAWAL_REQUESTS { get; set; }
        public string WITHDRAWAL_PROCESSED { get; set; }
        public string AVAILABLE_WITHDRAWAL { get; set; }
        public string NET_DEPOSIT { get; set; }
        public string NET_DEPOSIT_BONUS { get; set; }
        public string BONUS { get; set; }
        public string PLATFORM { get; set; }
        public string CREATE_DEPOSIT { get; set; }
        public string DEPOSIT_AMOUNT { get; set; }
        public string DEPOSIT_METHOD { get; set; }
        public string TRANSACTION_CURRENCY { get; set; }
        public string TRANSACTION_ID { get; set; }
        public string CC_LAS_4_DIGITS { get; set; }
        public string DEPOSIT_DEMO { get; set; }
        public string AMOUNT_TO_CREDIT { get; set; }
        public string METHOD { get; set; }
        public string DEPOSIT_BONUS { get; set; }
        public string DEMO_DEPOSIT { get; set; }
        public string ASSETS_ON_FRONT_WAS_SUCCESSFULLY_UPDATED { get; set; }
        public string ADVANCE { get; set; }
        public string LEADS_STATUS { get; set; }
        public string CREATE_STATUS { get; set; }
        public string STATUS_NAME { get; set; }
        public string EDIT_STATUS { get; set; }
        public string ENTER_STATUS { get; set; }
        public string CHOOSE_A_COLOR { get; set; }
        public string BLOCK_OPEN_TRADE { get; set; }
        public string ADD_NEW { get; set; }
        public string SALES_AGENTS_SALARY { get; set; }
        public string CREATE_SALARY { get; set; }
        public string CREATE_ACCOUNT_TYPES { get; set; }
        public string ADD_CHARGEBACK { get; set; }
        public string SPLIT_WITHDRAWAL { get; set; }
        public string AGENTS { get; set; }
        public string TARGET { get; set; }
        public string FAIL { get; set; }
        public string SUCCESS { get; set; }
        public string SA_BALANCE { get; set; }
        public string TRANSFER_TO_SA { get; set; }
        public string TRANSFER_TO_BALANCE { get; set; }
        public string AVAILABLE_BALANCE { get; set; }
        public string TRANSFER { get; set; }
        public string ATTRIBUTION_RULES { get; set; }
        public string CREATE_RULE { get; set; }
        public string CHOOSE_TYPE { get; set; }
        public string FTD_SELLERS { get; set; }
        public string RANDOMLY { get; set; }
        public string EQUALLY { get; set; }
        public string RETENTION_SELLERS { get; set; }
        public string RETENTION_TYPE { get; set; }
        public string AT_FIRST_DEPOSIT { get; set; }
        public string AT_VOLUME_OF { get; set; }
        public string NEVER { get; set; }
        public string ASSIGN_METHOD { get; set; }
        public string SELLER_WITH_MINIMUM_CLIENT { get; set; }
        public string RANDOM { get; set; }
        public string ACCESS_ONLY_FOR_CUSTOMERS { get; set; }
        public string EQUITY { get; set; }
        public string ADD_NAME { get; set; }
        public string ENTER_GROUP_NAME { get; set; }
        public string AVAILABLE { get; set; }
        public string CALL_CLIENT { get; set; }
        public string SWITCH_TO_CUSTOMER { get; set; }
        public string CHANGE_FEED_MESSAGE { get; set; }
        public string CHANGE_BANNER_MESSAGE { get; set; }
        public string CHANGE_TRADE_GROUP { get; set; }
        public string BLOCKED { get; set; }
        public string CUSTOMER_WAS_SUCCESSFULLY_UPDATED { get; set; }
        public string TOTAL_CUSTOMERS { get; set; }
        public string TOTAL_DEPOSITS { get; set; }
        public string TOTAL_WITHDRAWALS { get; set; }
        public string SALES_PERFOMANCE { get; set; }
        public string ALL_WITHDRAWALS { get; set; }
        public string ENTER_DELETE_REASON { get; set; }
        public string REOPEN_TRADES { get; set; }
        public string THIS_ACTION_WILL_DELETE_PL_GENERATED_FOR_THIS_TRANSACTION { get; set; }
        public string BLOCK_CRM_USER_AFTER_LOGIN_TRIES { get; set; }
        public string BLOCK_TRADE_USER_AFTER_LOGIN_TRIES { get; set; }
        public string LOGIN_ATTEMPTS_WAS_SUCCESSFULLY_UPDATED { get; set; }
        public string MESSAGE_TO_DISPLAY_FOR_BLOCK_USERS { get; set; }
        public string WEBSITE_LOGIN { get; set; }
        public string WEBSITE { get; set; }
        public string BLOCK_REGISTER { get; set; }
        public string BLOCK_LOGIN { get; set; }
        public string BLOCK_COUNTRIES { get; set; }
        public string REDIRECT_TO { get; set; }
        public string MINIMUM_DEPOSIT { get; set; }
        public string MAXIMUM_DEPOSIT { get; set; }
        public string REGISTRATION_SETTINGS { get; set; }
        public string DEFAULT_COMPLIANCE_STATUS { get; set; }
        public string EDIT_COMPANY_INFORMATION { get; set; }
        public string COMPANY_NAME { get; set; }
        public string MAIN_LOGO_FOR_LIGHT_MODE { get; set; }
        public string MAIN_LOGO_FOR_DARK_MODE { get; set; }
        public string MOBILE_LOGO { get; set; }
        public string ERP_LOGO { get; set; }
        public string LOGO_LINK_TARGET { get; set; }
        public string SAME_WINDOW { get; set; }
        public string NEW_WINDOW { get; set; }
        public string GROUP_NAMES { get; set; }
        public string LOGO_LINK_REDIRECT { get; set; }
        public string HOME_PAGE { get; set; }
        public string TRAD_PLATFORM { get; set; }
        public string TRADING_LOGO_SIZE { get; set; }
        public string LOGIN_LOGO_SIZE { get; set; }
        public string WIDTH { get; set; }
        public string HEIGHT { get; set; }
        public string COMPANY_OFFSHORE { get; set; }
        public string COMPANY_DETAILS { get; set; }
        public string FOOTER_TEXT { get; set; }
        public string UPLOAD_DOD_DOCUMENT { get; set; }
        public string UPLOAD_DOD { get; set; }
        public string YES { get; set; }
        public string NO { get; set; }
        public string AFFILIATE_NAME_IS_REQUIRED { get; set; }
        public string DEAL_IS_REQUIRED { get; set; }
        public string CAMPAIGN_NAME_IS_REQUIRED { get; set; }
        public string CAMPAIGN_CODE_CANNOT_EXCEED_24_CHARACTERS { get; set; }
        public string CURRENCY_IS_REQUIRED { get; set; }
        public string NAME_IS_REQUIRED { get; set; }
        public string COMMISSION_IS_REQUIRED { get; set; }
        public string COMMISSION_HAS_TO_BE_100_OR_LESS { get; set; }
        public string LEVERAGE_IS_REQUIRED { get; set; }
        public string LEVERAGE_HAS_TO_BE_AT_LEAST_1 { get; set; }
        public string MAINTENANCE_IS_REQUIRED { get; set; }
        public string MAINTENANCE_HAS_TO_BE_100_0R_LESS { get; set; }
        public string MAINTENANCE_HAS_TO_BE_AT_LEAST_1 { get; set; }
        public string DISABLE_IP_VERIFICATION { get; set; }
        public string DISABLE_IP_VERIFICATION_WARNING { get; set; }
        public string DELETE_ROLE_WARNING { get; set; }
        public string MINIMUM_AMOUNT_IS_REQUIRED { get; set; }
        public string MINIMUM_AMOUNT_HAS_TO_BE_MORE_THAN_0 { get; set; }
        public string MINIMUM_STEP_IS_REQUIRED { get; set; }
        public string MINIMUM_STEP_HAS_TO_BE_MORE_THAN_0 { get; set; }
        public string SPREAD_IS_REQUIRED { get; set; }
        public string SPREAD_HAS_TO_BE_100_OR_LESS { get; set; }
        public string SWAP_LONG_IS_REQUIRED { get; set; }
        public string SWAP_LONG_HAS_TO_BE_100_OR_LESS { get; set; }
        public string SWAP_SHORT_IS_REQUIRED { get; set; }
        public string SWAP_SHORT_HAS_TO_BE_100_OR_LESS { get; set; }
        public string SWAP_TIME_IS_REQUIRED { get; set; }
        public string TYPE_IS_REQUIRED { get; set; }
        public string RETENTION_TYPE_IS_REQUIRED { get; set; }
        public string FTD_AGENT_IS_REQUIRED { get; set; }
        public string COUNTRY_IS_REQUIRED { get; set; }
        public string CITY_IS_REQUIRED { get; set; }
        public string HIDE_BOTTOM_BUTTONS { get; set; }
        public string NAME_MUST_BE_AT_LEAST_2_CHARACTERS { get; set; }
        public string NAME_CANNOT_EXCEED_60_CHARACTERS { get; set; }
        public string DEFAULT_NUMBER_MUST_BE_POSITIVE { get; set; }
        public string MAXIMUM_LENGTH_CANNOT_EXCEED_4_CHARACTERS { get; set; }
        public string MERCHANT_ID_IS_REQUIRED { get; set; }
        public string MERCHANT_PASSWORD_IS_REQUIRED { get; set; }
        public string SHOW_CONVERTED_AMOUNT { get; set; }
        public string ORDER_DESCRIPTION_IS_REQUIRED { get; set; }
        public string EMAIL_TYPE_IS_REQUIRED { get; set; }
        public string LANGUAGE_IS_REQUIRED { get; set; }
        public string EMAIL_SUBJECT_IS_REQUIRED { get; set; }
        public string EMAIL_NAME_IS_REQUIRED { get; set; }
        public string AMOUNT_TO_CREDIT_IS_REQUIRED { get; set; }
        public string METHOD_IS_REQUIRED { get; set; }
        public string INVALID_SPLIT_AMOUNT { get; set; }
        public string DEPOSIT_AMOUNT_IS_REQUIRED { get; set; }
        public string DEPOSIT_METHOD_IS_REQUIRED { get; set; }
        public string AMOUNT_CAN_NOT_BE_GREATER_THAN_BALANCE { get; set; }
        public string PSP_IS_REQUIRED { get; set; }
        public string CHARACTERS { get; set; }
        public string VIEW { get; set; }
        public string PLEASE_ENTER_AMOUNT_OF_TRADES_YOURE_ABOUT_TO_REOPEN { get; set; }
        public string PLEASE_ENTER_AMOUNT_OF_TRADES_YOURE_ABOUT_TO_DELETE { get; set; }
        public string PLEASE_ENTER_AMOUNT_OF_TRADES_YOURE_ABOUT_TO_CLOSE { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_DELETE { get; set; }
        public string WITHDRAWAL_OPEN_POSITIONS_WARNING { get; set; }
        public string TRANSACTIONS_WARNING { get; set; }
        public string WITHDRAWAL_NO_AVAILABLE { get; set; }
        public string UPDATING_EMAIL_TEMPLATE_TITLE { get; set; }
        public string UPDATING_EMAIL_TEMPLATE_CONTENT { get; set; }
        public string ALL_THE_USERS_OF_THIS_GROUP_WILL_BE_ASSIGN_TO_THE_DEFAULT_TRADE_GROUP { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_CLOSE { get; set; }
        public string PLEASE_ENTER_TRADE_ID { get; set; }
        public string ENTER_EXPORT_ADMIN_EMAIL { get; set; }
        public string THIS_EMAIL_SHOULD_BE_REGISTERED { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_REOPEN { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_REOPEN_SELECTED_TRADES { get; set; }
        public string STARTING_SPREAD { get; set; }
        public string CURRENT_SPREAD { get; set; }
        public string STARTING_LEVERAGE { get; set; }
        public string CURRENT_LEVERAGE { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_RELEASE { get; set; }
        public string DID_NOT_DELETED { get; set; }
        public string THE_FOLLOWING_USERS_WAS_NOT_DELETED { get; set; }
        public string DELETE_COMMENTS_OF_CUSTOMERS_SELECTED { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO { get; set; }
        public string DELETE_THE_CUSTOMERS_SELECTED { get; set; }
        public string SWITCH_LEADS_TO_CUSTOMERS { get; set; }
        public string THE_EMAIL_TYPE_AND_LANGUAGE_ARE_ALREADY_IN_USE { get; set; }
        public string EMAIL_BODY_SHOULD_BE_LESS_THEN_0_5_MB { get; set; }
        public string YOU_SHOULD_ADD_EMAIL_BODY { get; set; }
        public string MAXIMUM_IMAGE_SIZE_IS_1_MB { get; set; }
        public string MAXIMUM_IMAGE_SIZE_IS_15_MB { get; set; }
        public string AMOUNT_IS_REQUIRED { get; set; }
        public string COMPANY_NAME_IS_REQUIRED { get; set; }
        public string LOGO_LINK_TARGET_IS_REQUIRED { get; set; }
        public string LOGO_LINK_REDIRECT_IS_REQUIRED { get; set; }
        public string GLOBAL_PERMISSIONS { get; set; }
        public string CLIENT_PROFILE { get; set; }
        public string VERIFICATION_FAILED_CONTACT_SUPPORT { get; set; }
        public string DEVICE_IS_NOT_VERIFIED { get; set; }
        public string DEVICE_IS_VERIFIED { get; set; }
        public string YOU_WILL_BE_REDIRECTED { get; set; }
        public string WAITING_FOR_VERIFICATION { get; set; }
        public string LINK_HAS_BEEN_SENT_TO_YOUR_EMAIL { get; set; }
        public string LINK_HAS_BEEN_SENT_TO_CLIENT_EMAIL { get; set; }
        public string KYC_CC_BACK { get; set; }
        public string KYC_CC_FRONT { get; set; }
        public string CONTACT_SUPPORT { get; set; }
        public string PASSWORD_WAS_NOT_CHANGED { get; set; }
        public string CHANGE_PASSWORD { get; set; }
        public string TOTAL_FOR { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string ACCOUNT_TYPE_IS_REQUIRED { get; set; }
        public string GROUP_NAME_IE_REQUIRED { get; set; }
        public string NOTIFICATION_LOGIN { get; set; }
        public string NOTIFICATION_LOGOUT { get; set; }
        public string NOTIFICATION_CLIENTS_IMPORT { get; set; }
        public string NOTIFICATION_OPEN_TRADE { get; set; }
        public string NOTIFICATION_CLOSE_TRADE { get; set; }
        public string NOTIFICATION_TRADE_ORDER_ACTIVATED { get; set; }
        public string NOTIFICATION_FILE_UPLOAD { get; set; }
        public string NOTIFICATION_WITHDRAWAL_PROCESSED { get; set; }
        public string NOTIFICATION_WITHDRAWAL_STATUS_CHANGED { get; set; }
        public string NOTIFICATION_WITHDRAWAL_REQUEST { get; set; }
        public string NOTIFICATION_DEPOSIT { get; set; }
        public string NOTIFICATION_DIRECT_REGISTER { get; set; }
        public string NOTIFICATION_CAMPAIGN_OR_API_REGISTER { get; set; }
        public string NOTIFICATION_APPOINTMENT { get; set; }
        public string NOTIFICATION_RESET_PASSWORD { get; set; }
        public string NOTIFICATION_DEPOSIT_PAGE { get; set; }
        public string NOTIFICATION_TP_CLOSE_TRADE { get; set; }
        public string NOTIFICATION_SL_CLOSE_TRADE { get; set; }
        public string NOTIFICATION_MARGIN_CLOSE_TRADE { get; set; }
        public string NOTIFICATION_REACH_MARGIN_LIMIT { get; set; }
        public string NOTIFICATION_CALL { get; set; }
        public string NOTIFICATION_REDIRECT_TO_PSP { get; set; }
        public string HAS_CALLED { get; set; }
        public string RECENT_ACTIVITIES { get; set; }
        public string ADDED_BONUS_OF { get; set; }
        public string ADDED_DEPOSIT_OF { get; set; }
        public string CHANGE { get; set; }
        public string GROUP_FROM { get; set; }
        public string CHANGE_WD_FROM { get; set; }
        public string FROM_SA_TO_BALANCE { get; set; }
        public string CHARGED_BACK { get; set; }
        public string MOVE { get; set; }
        public string MOVED { get; set; }
        public string FROM_BALANCE_TO_SA { get; set; }
        public string CLOSE_TRADE { get; set; }
        public string DELETE_TRADE { get; set; }
        public string DELETE_USER { get; set; }
        public string REGISTER { get; set; }
        public string REGISTERED_FROM { get; set; }
        public string LOGGED_INTO_ACCOUNT { get; set; }
        public string HAS_CLOSED_DUE_TO_TP { get; set; }
        public string HAS_CLOSED_DUE_TO_SL { get; set; }
        public string HAS_LOGGED_IN { get; set; }
        public string AND_HAS_LOGGED_OUT_AT { get; set; }
        public string AND_IS_CURRENTLY_ONLINE { get; set; }
        public string LOGGED_IN_ON { get; set; }
        public string ISO_CODE { get; set; }
        public string DELETE_CUSTOMER { get; set; }
        public string RECEIVED_COMMENT { get; set; }
        public string OFFICE_TIME { get; set; }
        public string ONLINE { get; set; }
        public string LONDON { get; set; }
        public string AUSTRALIA { get; set; }
        public string LOCAL_GMT { get; set; }
        public string DEPOSIT_AMOUNT_CAN_NOT_BE_NEGATIVE { get; set; }
        public string BONUSES { get; set; }
        public string SCREEN_CAPTURE { get; set; }
        public string HAD_OPEN_TRADE { get; set; }
        public string ONLINE_CUSTOMERS { get; set; }
        public string SALARY_TYPE { get; set; }
        public string YOU_ALREADY_HAVE_THIS_LANGUAGE { get; set; }
        public string LANGUAGES_TRADING_PLATFORM { get; set; }
        public string ADD_LANGUAGE { get; set; }
        public string NEW { get; set; }
        public string KEY { get; set; }
        public string NAME { get; set; }
        public string DEFAULT_TRANSLATION { get; set; }
        public string TRANSLATION { get; set; }
        public string LANGUAGE_NAME_IS_REQUIRED { get; set; }
        public string LANGUAGE_CODE_IS_REQUIRED { get; set; }
        public string LIST_OF_COUNTRIES { get; set; }
        public string LIST_OF_CURRENCIES { get; set; }
        public string REGULATIONS { get; set; }
        public string CHARGEBACK_MONTH_LIMIT { get; set; }
        public string PLEASE_ENTER_DEPOSIT_ID { get; set; }
        public string YOU_CAN_NOT_MAKE_CHARGEBACK_PLEASE_CONTACT_SUPPORT { get; set; }
        public string DO_YOU_WANT_T0_MAKE_CHARGEBACK_OF { get; set; }
        public string CMS { get; set; }
        public string UNASSIGN { get; set; }
        public string GLOBAL_EVENTS { get; set; }
        public string THIS_ACTION_CANNOT_BE_REVERSED { get; set; }
        public string INCLUDING_PNL_OF { get; set; }
        public string OPTIONS_CLIENT { get; set; }
        public string BRAND_CAN_WRITE_FREE_TEXT_IN_BONUS { get; set; }
        public string CREATE_TEXT { get; set; }
        public string ENTER_BONUS_TEXT { get; set; }
        public string DELETED { get; set; }
        public string RESET_EQUITY { get; set; }
        public string EQUITY_HAS_BEEN_RESET { get; set; }
        public string EQUITY_HAS_NOT_BEEN_RESET { get; set; }
        public string DELETE_BONUS { get; set; }
        public string DELETE_TRADES { get; set; }
        public string CLOSE_TRADES { get; set; }
        public string CLIENTS { get; set; }
        public string UNASSIGNED_CLIENTS { get; set; }
        public string SAVE_FILTER { get; set; }
        public string LOAD_FILTER { get; set; }
        public string FILTER_NAME { get; set; }
        public string SORT { get; set; }
        public string DELETE_THE_CLIENTS_SELECTED { get; set; }
        public string MERCHANT_ACCOUNT_ID { get; set; }
        public string MERCHANT_ACCOUNT_KEY { get; set; }
        public string MERCHANT_ACCOUNT_USER_NAME { get; set; }
        public string MERCHANT_ACCOUNT_PASSWORD { get; set; }
        public string STATEMENT_TEXT { get; set; }
        public string PRODUCTION_URL { get; set; }
        public string IS_REQUIRED { get; set; }
        public string ADDITIONAL_PSP_INFORMATION { get; set; }
        public string COPY_URL { get; set; }
        public string DEPOSIT_DETAILS { get; set; }
        public string IMPORT_LEAD_STATUS { get; set; }
        public string FILE_UPLOAD_IS_PROCESSING { get; set; }
        public string TOTAL_LEADS_IMPORTED_SUCCESSFULLY { get; set; }
        public string RISK_CUSTOMERS { get; set; }
        public string GENERATE_API_KEY { get; set; }
        public string COPY { get; set; }
        public string DATE_OF_DEPOSIT { get; set; }
        public string TRANSACTION_TYPE { get; set; }
        public string TRANSACTION_STATUS { get; set; }
        public string AMOUNT_OF_DEPOSIT { get; set; }
        public string ORIGINAL_AMOUNT { get; set; }
        public string ORIGINAL_CURRENCY { get; set; }
        public string LAST_DIGITS { get; set; }
        public string REJECT_REASON { get; set; }
        public string DATE_OF_BONUS { get; set; }
        public string AMOUNT_OF_BONUS { get; set; }
        public string STATUS { get; set; }
        public string AMOUNT_OF_WITHDRAWAL { get; set; }
        public string DATE_OF_REQUEST { get; set; }
        public string DATE_OF_UPDATE { get; set; }
        public string PSP { get; set; }
        public string AMOUNT_OF_CHARGEBACK { get; set; }
        public string ASSIGNED_TO { get; set; }
        public string EXPORT { get; set; }
        public string IMPORT_EXPORT { get; set; }
        public string MORE_DETAILS { get; set; }
        public string RELEASE { get; set; }
        public string DELETE_COMMENT { get; set; }
        public string ASSIGN_TO_SALES_AGENT { get; set; }
        public string CHANGE_CAMPAIGN { get; set; }
        public string CHANGE_STATUS { get; set; }
        public string DELETE_CLIENTS { get; set; }
        public string PSP_POSITION { get; set; }
        public string BANK_TRANSFER { get; set; }
        public string WALLET_TO_WALLET { get; set; }
        public string PASSWORD_PATTERN { get; set; }
        public string PASSWORD_ALLOWED_CHARACTERS { get; set; }
        public string OPEN_IN_NEW_TAB { get; set; }
        public string REDIRECT_BY_EMAIL { get; set; }
        public string SAVE_AND_CREATE_ANOTHER_USER { get; set; }
        public string APPROVED { get; set; }
        public string REJECTED { get; set; }
        public string IN_PROCESS { get; set; }
        public string CANCELED { get; set; }
        public string SEND_KEY { get; set; }
        public string SEND_API_KEY { get; set; }
        public string API_KEY_WAS_SENT_TO { get; set; }
        public string MY_TZ { get; set; }
        public string NO_NOTIFICATIONS { get; set; }
        public string DELETED_CAMPAIGN { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_DELETE_CAMPAIGN { get; set; }
        public string PLATFORM_NAME { get; set; }
        public string PLANNING_TIME { get; set; }
        public string UPDATE_USER { get; set; }
        public string USER_FINANCE_DATA_HAS_NOT_BEEN_UPDATED { get; set; }
        public string USER_FINANCE_DATA_WAS_UPDATED_SUCCESSFULLY { get; set; }
        public string LAST_REGISTRATION { get; set; }
        public string NO_LEADS_FOUND { get; set; }
        public string CHANGE_PASSWORD_NOW { get; set; }
        public string PASSWORDS_DO_NOT_MATCH { get; set; }
        public string YOUR_PASSWORD_IS_ABOUT_TO_EXPIRE { get; set; }
        public string LINK_FOR_CHANGE_PASSWORD_HAS_BEEN_SENT_TO_YOUR_EMAIL { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_CALL { get; set; }
        public string EURO_AMOUNT { get; set; }
        public string REQUEST_DATE { get; set; }
        public string PROCEED_DATE { get; set; }
        public string CHARGEBACK_DATE { get; set; }
        public string FILES { get; set; }
        public string FILES_LIST { get; set; }
        public string DELETE_CHOOSED_FILES { get; set; }
        public string UPLOAD_FILES { get; set; }
        public string NO_FILES_TO_UPLOAD { get; set; }
        public string FILES_TO_UPLOAD { get; set; }
        public string FILE_NAME { get; set; }
        public string CALL { get; set; }
        public string ONLINE_CLIENTS { get; set; }
        public string CHANGE_AVATAR { get; set; }
        public string LEADERDOARD_PERMIT { get; set; }
        public string OPEN_SALES_DASHBOARD { get; set; }
        public string SALES_DASHBOARD_BILL_PRICE { get; set; }
        public string SALES_DASHBOARD_ACTIVE { get; set; }
        public string MONTHLY_PRICE { get; set; }
        public string SALES_DASHBOARD_PERMIT { get; set; }
        public string REDIRECT { get; set; }
        public string OPEN_LEADERBOARD { get; set; }
        public string DOWNLOAD { get; set; }
        public string NEW_PASSWORD { get; set; }
        public string SET_PASSWORD { get; set; }
        public string SET_USER_PASSWORD { get; set; }
        public string PASSWORD_HAS_BEEN_CHANGED_SUCCESSFULLY { get; set; }
        public string EDIT_TRADE { get; set; }
        public string STATUS_IS_REQUIRED { get; set; }
        public string SWAP_COMMISSION_HAS_TO_BE_100_OR_LESS { get; set; }
        public string DIALER_CAMPAIGN { get; set; }
        public string SET_SUSPICIOUS_PNL_PERCENTAGE { get; set; }
        public string SUSPICIOUS_PROFIT { get; set; }
        public string FEED { get; set; }
        public string FEED_NAME { get; set; }
        public string CREATE_FEED { get; set; }
        public string CHOOSE_FEED_TYPE { get; set; }
        public string FEED_NAME_IS_REQUIRED { get; set; }
        public string BANNER { get; set; }
        public string BANNER_NAME { get; set; }
        public string CREATE_BANNER { get; set; }
        public string CHOOSE_BANNER_TYPE { get; set; }
        public string BANNER_NAME_IS_REQUIRED { get; set; }
        public string MARGIN_CALL { get; set; }
        public string SET_MARGIN_CALL_PERCENTAGE { get; set; }
        public string SEND_NOTIFICATION { get; set; }
        public string SEND_EMAIL { get; set; }
        public string SENT_RESET_PASSWORD_LINK { get; set; }
        public string TERMS_AND_CONDITIONS { get; set; }
        public string TERMS_AND_CONDITIONS_URL { get; set; }
        public string EXPORT_DATA { get; set; }
        public string SWITCH_THE_SELECTED_LEADS_TO_CUSTOMERS { get; set; }
        public string CUSTOM_PAGE_BODY { get; set; }
        public string FEED_BODY { get; set; }
        public string BANNER_BODY { get; set; }
        public string OTHER_PSP { get; set; }
        public string OTHER { get; set; }
        public string YOU_REQUEST_MAY_TAKE_SOME_TIME_DUE_TO_THE_LARGE_DATA { get; set; }
        public string HIDE { get; set; }
        public string UNHIDE { get; set; }
        public string TOGGLE { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_HIDE { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_TOGGLE { get; set; }
        public string WITHDRAWAL_BONUS { get; set; }
        public string ASSIGN_WITHDRAWAL { get; set; }
        public string ASSIGN_CHARGEBACK { get; set; }
        public string CHOOSE_SALES_AGENT { get; set; }
        public string EDIT_COMMENT_CREATED_ON { get; set; }
        public string UNASSIGNED { get; set; }
        public string APPROVE { get; set; }
        public string NOT_NOW { get; set; }
        public string HIDDEN { get; set; }
        public string DELETED_CLIENT_FILE { get; set; }
        public string DELETE_FILTER { get; set; }
        public string CLEAR_FILTERS { get; set; }
        public string CURRENT_FILTER { get; set; }
        public string NO_FILTER_SELECTED { get; set; }
        public string PIXEL_GRAPH { get; set; }
        public string CHANGED_CLIENT_INFORMATION { get; set; }
        public string CHANGED_FEED_MESSAGE { get; set; }
        public string CHANGED_BANNER_MESSAGE { get; set; }
        public string ASSIGNED_DEPOSIT_FROM { get; set; }
        public string OTHER_PSP_TEXT { get; set; }
        public string THIS_MONTH { get; set; }
        public string BANK_TITLE { get; set; }
        public string BANK_BODY { get; set; }
        public string WALLET_TITLE { get; set; }
        public string WALLET_BODY { get; set; }
        public string WALLET_WALLET { get; set; }
        public string WALLET_FOOTER { get; set; }
        public string WITHDRAWAL_STATUS_HAS_BEEN_CHANGED_SUCCESSFULLY { get; set; }
        public string CHOOSE_METHOD { get; set; }
        public string ADD_MORE_INFO { get; set; }
        public string AGENT_NAME { get; set; }
        public string LAST_4_DIGITS { get; set; }
        public string CHAT_MESSAGES { get; set; }
        public string CHRONO_ASSETS { get; set; }
        public string STOP_LOSS_TAKE_PROFIT_FEES { get; set; }
        public string BOOST_OPTIONS { get; set; }
        public string TIME_PERIODS { get; set; }
        public string PLEASE_SELECT_6 { get; set; }
        public string CREATE_CHAT_MESSAGE { get; set; }
        public string CHAT_MESSAGE_TYPE { get; set; }
        public string CHAT_MESSAGE_LANGUAGE { get; set; }
        public string SAVE_AND_CREATE_ANOTHER_CHAT_MESSAGE { get; set; }
        public string WELCOME_CHAT_SENTENCE { get; set; }
        public string OFFLINE_CHAT_SENTENCE { get; set; }
        public string CLOSE_CHAT_SENTENCE { get; set; }
        public string CHAT_DISABLED_FOR_AGENT_SENTENCE { get; set; }
        public string USER_JOINED_CHAT_SENTENCE { get; set; }
        public string USER_LEFT_CHAT_SENTENCE { get; set; }
        public string CONTENT_IS_REQUIRED { get; set; }
        public string CHAT_COLOR { get; set; }
        public string CURRENT_CHAT_COLOR { get; set; }
        public string CHANGE_COLOR { get; set; }
        public string PARTICIPANTS { get; set; }
        public string FORBID_TO_JOIN_CHAT_MESSAGE { get; set; }
        public string CHAT_HISTORY { get; set; }
        public string CONFIRM_DEPOSIT { get; set; }
        public string YOU_ARE_ABOUT_TO_ADD { get; set; }
        public string TO_THIS_ACCOUNT { get; set; }
        public string CLICK_CONFIRM_TO_PROCEED { get; set; }
        public string EXPORT_DATA_EMAIL_URL { get; set; }
        public string ADMIN_EMAILS { get; set; }
        public string COPIED_SUCCESSFULLY { get; set; }
        public string EMAIL_WITH_DOWNLOAD_LINK_HAS_BEEN_SENT_TO_ADMINISTRATOR { get; set; }
        public string PLEASE_CHECK_USER_AVAILABLE_OR_CONTACT_ADMIN { get; set; }
        public string EXPORTED_TABLE { get; set; }
        public string DOWNLOADED_EXPORT_LINK { get; set; }
        public string EXPORT_LINK_WAS_SENT_TO_ADMINS_EMAIL_BY_USER { get; set; }
        public string WITHDRAWAL_TITLE { get; set; }
        public string ENTER_WITHDRAWAL_TITLE_TEXT { get; set; }
        public string CLICK_TO_CALL { get; set; }
        public string _2_MONTHS_AGO { get; set; }
        public string _2_DAYS_AGO { get; set; }
        public string ENABLE_TWO_FACTOR { get; set; }
        public string PLEASE_ENTER_YOUR_AUTHENTICATOR_APP_CODE { get; set; }
        public string PLEASE_SCAN_CODE_TO_YOUR_AUTHENTICATOR_APP { get; set; }
        public string ASK_ADMIN_TO_RESET_2FACTOR_CODE { get; set; }
        public string RESET_REQUEST_WAS_SENT_TO_ADMIN { get; set; }
        public string RESET_TWO_FACTOR { get; set; }
        public string SCAN_CODE_AGAIN { get; set; }
        public string TOKEN_MUST_BE_A_SIX_DIGITS_NUMBER { get; set; }
        public string TWO_FACTOR_SETTINGS { get; set; }
        public string EXPORT_ADMIN_EMAILS { get; set; }
        public string TWO_FACTOR_ADMIN_EMAILS { get; set; }
        public string SUSPICIOUS_PROFIT_ADMIN_EMAILS { get; set; }
        public string NEW_DEVICE_LOGIN_NOTIFICATION { get; set; }
        public string TRADE_ABOUT_TO_EXPIRE { get; set; }
        public string TRADE_ABOUT_TO_ROLL_OVER { get; set; }
        public string CONVERTER { get; set; }
        public string EXCLUDED_CURRENCIES { get; set; }
        public string CHOOSE_TITLE { get; set; }
        public string EDIT_CLIENT_PROFILE_RESTRICTIONS { get; set; }
        public string EDIT_DOC_SECTION_RESTRICTIONS { get; set; }
        public string CREDIT_DEBIT_CARD_DOCUMENTATION { get; set; }
        public string SHOW_AVAILABLE_TO_WITHDRAWAL { get; set; }
        public string SHOW_CLIENT_NAME { get; set; }
        public string SHOW_TRADING_VOLUME { get; set; }
        public string SHOW_DOC_SECTION { get; set; }
        public string MAP { get; set; }
        public string MAP_CAMPAIGNS_STATISTICS { get; set; }
        public string STATISTICS { get; set; }
        public string ACTIVATE_PENDING_TRADE { get; set; }
        public string REMIND_ABOUT_DEPOSIT_IN { get; set; }
        public string HOURS { get; set; }
        public string REMIND_DEPOSIT { get; set; }
        public string CHOOSE_WITHDRAWAL_PAYMENT_METHOD { get; set; }
        public string AMOUNT_TO_WITHDRAWAL { get; set; }
        public string BANK { get; set; }
        public string BANK_NAME_IS_REQUIRED { get; set; }
        public string CREDIT_CARD { get; set; }
        public string BTC_WALLET { get; set; }
        public string CREATE_WITHDRAWAL { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_WITHDRAW { get; set; }
        public string FROM_THIS_ACCOUNT { get; set; }
        public string AVAILABLE_TO_WITHDRAWAL { get; set; }
        public string AMOUNT_CAN_NOT_EXCEED_AVAILABLE_WITHDRAWAL { get; set; }
        public string PAYMENT_DETAILS { get; set; }
        public string BANK_NAME { get; set; }
        public string ACCOUNT_NAME { get; set; }
        public string SWIFT { get; set; }
        public string IBAN { get; set; }
        public string BANK_ADDRESS { get; set; }
        public string BANK_BRANCH { get; set; }
        public string CARD_OWNER_NAME { get; set; }
        public string CARD_LAST_DIGITS { get; set; }
        public string EXPIRE_DATE { get; set; }
        public string FULL_BTC_WALLET_ADDRESS { get; set; }
        public string BTC_ADDRESS_CONFIRMATION { get; set; }
        public string FIRST_FOUR_DIGITS { get; set; }
        public string LAST_FOUR_DIGITS { get; set; }
        public string BY_CLICKING_ON_THE_BUTTON_BELOW_YOU_AGREE_TO_THE_TERMS_AND_CONDITIONS { get; set; }
        public string WITHDRAWAL_REQUEST_SENT { get; set; }
        public string INVALID_WALLET_ADDRESS { get; set; }
        public string INVALID_CHARACTERS_VALIDATION { get; set; }
        public string HAS_SENT_EMAIL { get; set; }
        public string ACTIVATE_USER { get; set; }
        public string BLOCKED_USER { get; set; }
        public string DOCUMENT { get; set; }
        public string CREATE_DOCUMENT { get; set; }
        public string CREATE_DOD { get; set; }
        public string CHOOSE_DOCUMENT_TYPE { get; set; }
        public string DOCUMENT_TYPE { get; set; }
        public string DOD_TYPE { get; set; }
        public string DOCUMENT_BODY { get; set; }
        public string DOD_BODY { get; set; }
        public string DOCUMENT_TYPE_IS_REQUIRED { get; set; }
        public string DOD { get; set; }
        public string CUSTOM { get; set; }
        public string PREVIEW { get; set; }
        public string FAILED_TO_RETRIEVE_REQUESTED_DOCUMENT { get; set; }
        public string DOCUMENT_NAME { get; set; }
        public string DOD_NAME { get; set; }
        public string DOCUMENT_NAME_IS_REQUIRED { get; set; }
        public string DOD_NAME_IS_REQUIRED { get; set; }
        public string PLEASE_SIGN_THIS_DOCUMENT_IN_THE_BOX_BELOW { get; set; }
        public string DOCUMENTS { get; set; }
        public string CLIENT_DOCUMENTS { get; set; }
        public string CAN_ONLY_REOPEN_UP_TO_25_EACH_TIME { get; set; }
        public string ERROR_GETTING_CLIENT_DOCUMENTS { get; set; }
        public string SIGNED { get; set; }
        public string DOCUMENTS_AND_FILES { get; set; }
        public string PLEASE_SIGN_THIS_DOCUMENT_HERE { get; set; }
        public string FAILED_TO_UPLOAD_FILE { get; set; }
        public string FILE_HAS_BEEN_UPLOADED { get; set; }
        public string CREATED_NEW_DOCUMENT { get; set; }
        public string YOU_SHOULD_ADD_DOCUMENT_BODY { get; set; }
        public string DOCUMENT_BODY_SHOULD_BE_LESS_THEN_0_5_MB { get; set; }
        public string GROUP_UPDATE_IN_PROGRESS { get; set; }
        public string LOADING { get; set; }
        public string CHAT_VARIABLES { get; set; }
        public string VALUE_SHOULD_BE_MAXIMUM_15 { get; set; }
        public string TRADING_VOLUME_TOOLTIP_TEXT { get; set; }
        public string SWAP_TOOLTIP_TEXT { get; set; }
        public string COMMISSION_TOOLTIP_TEXT { get; set; }
        public string TRADES_TOTAL_VALUE { get; set; }
        public string COMPANY_FULL_ADDRESS { get; set; }
        public string EXPORT_TABLE { get; set; }
        public string GLOBAL_VARIABLES_NOT_AVAILABLE { get; set; }
        public string MARKET_EXPOSURE { get; set; }
        public string FAILED_TO_RETRIEVE_TRADES { get; set; }
        public string LONG_POSITION { get; set; }
        public string SHORT_POSITION { get; set; }
        public string ON { get; set; }
        public string TOP_ASSETS_VOLUME { get; set; }
        public string TOTAL_EXPOSURE { get; set; }
        public string SAMPLE_EXPOSURE_ASSETS { get; set; }
        public string BUY { get; set; }
        public string SELL { get; set; }
        public string EXPOSURE { get; set; }
        public string SAMPLE_PENDING_ORDERS_ASSETS { get; set; }
        public string PENDING_ORDERS { get; set; }
        public string CLICK_TO_EXPORT { get; set; }
        public string YOUR_USER_MUST_BE_LOGGED_IN_TO_VIEW_EXPORT_FILES { get; set; }
        public string INVALID_EXPORT_LINK { get; set; }
        public string EXPORT_IS_NOT_READY { get; set; }
        public string PLEASE_DO_NOT_USE_EXPORT_LINK_WITH_SUPERADMIN_USER { get; set; }
        public string SEARCH { get; set; }
        public string FROM_LOGIN_LINK { get; set; }
        public string GET_SA_BALANCE_FAILED { get; set; }
        public string GETTING_TIMELINES { get; set; }
        public string RANDOM_ASSIGN_TO_SALES_AGENTS { get; set; }
        public string SHOW_HIDDEN_PSPS { get; set; }
        public string SHOW_VISIBLE_PSPS { get; set; }
        public string ARE_YOU_SURE_YOU_WANT_TO_HIDE_PSP { get; set; }
        public string GENERAL_DOD { get; set; }
        public string CHANGED_COMPLIANCE_STATUS_FROM { get; set; }
        public string DUE_TO_SUSPICIOUS_PROFIT { get; set; }
        public string COPIED_TO_CLIPBOARD { get; set; }
        public string WITHDREW_BONUS_OF { get; set; }
        public string ADMIN_EMAILS_FOR_FTD { get; set; }
        public string ADMIN_EMAILS_FOR_DEPOSIT { get; set; }
        public string ADMIN_DEPOSIT { get; set; }
        public string ADMIN_DEPOSIT_FTD { get; set; }
        public string ADMIN_EMAIL_HAS_TO_BE_ASSIGNED_TO_CRM_USER { get; set; }
        public string INVALID { get; set; }
        public string VALID { get; set; }
        public string FAILED_TO_UPDATE_DOCUMENT_STATUS { get; set; }
        public string DOCUMENT_STATUS_UPDATE_SUCCESSFUL { get; set; }
        public string WAITING { get; set; }
        public string GOT_IT { get; set; }
        public string CHANGED_DOCUMENT_STATUS_MESSAGE { get; set; }
        public string FROM { get; set; }
        public string DELETED_DOCUMENT { get; set; }
        public string CAN_NOT_CHANGE_STATUS_OF_NOT_UPLOADED_DOCUMENT { get; set; }
        public string SYSTEM_DOCUMENTS { get; set; }
        public string MASS_UNASSIGN_FROM_CAMPAIGN { get; set; }
        public string MASS_ASSIGN_TO_CAMPAIGN { get; set; }
        public string MASS_UNASSIGN_FROM_AGENT { get; set; }
        public string MASS_ASSIGN_TO_AGENT { get; set; }
        public string MASS_ASSIGN_TO_RANDOM_AGENTS { get; set; }
        public string MASS_CHANGE_BANNER { get; set; }
        public string MASS_CHANGE_STATUS { get; set; }
        public string CANNOT_REMOVE_BLOCKED_COUNTRY { get; set; }
        public string CONTACT_ACCOUNT_MANAGER { get; set; }
        public string _2_FA_SUCCESSFULLY_ENABLED { get; set; }
        public string YOU_CAN_DOWNLOAD_GOOGLE_AUTH_LINKS { get; set; }
        public string FOR_ANDROID_PHONE { get; set; }
        public string FOR_IPHONE { get; set; }
        public string _2_FA_CANT_BE_ENABLED { get; set; }
        public string _2_FACTOR_AUTHENTICATION { get; set; }
        public string YOU_ARE_ABOUT_TO_DISABLE_2_FA { get; set; }
        public string THANK_YOU { get; set; }
        public string SUPPORTED_CURRENCIES { get; set; }
        public string RECAPTCHA { get; set; }
        public string GET_V2_RECAPTCHA { get; set; }
        public string ACTIVATE_RECAPTCHA { get; set; }
        public string SITE_KEY { get; set; }
        public string BLOCK_USER_PERCENTAGE { get; set; }
        public string CLIENT_IS_BLOCKED { get; set; }
        public string SUSPICIOUS_PNL { get; set; }
        public string THIS_IS_A_REQUIRED_FIELD { get; set; }
        public string USER_COULDNT_REASSIGN_TO_CAMPAIGN { get; set; }
        public string USERS_COULDNT_REASSIGN_TO_CAMPAIGN { get; set; }
        public string CONTACT_SUPPORT_FOR_MORE_DETAILS { get; set; }
        public string TRADE_CLOSED_DUE_TO_MARGIN { get; set; }
        public string CHANGE_COMPLIANCE_STATUS { get; set; }
    }  
}
